import { PHRASES, type Phrase, type PhraseId } from "./phrases";
import { mergeTranslations } from "./translation-extra";

export type TranslationMap = Record<PhraseId, string>;

export interface LanguageDefinition {
  id: string;
  name: string;
  nativeName: string;
  flag: string;
  /** Optional script shown under the romanized/word form */
  scriptHint?: string;
  isCustom?: boolean;
  translations: TranslationMap;
}

function t(translations: Partial<Record<PhraseId, string>>): Record<PhraseId, string> {
  return translations as Record<PhraseId, string>;
}

export const LANGUAGES: LanguageDefinition[] = [
  {
    id: "es",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    translations: t({
      hello: "Hola",
      goodbye: "Adiós",
      thanks: "Gracias",
      please: "Por favor",
      yes: "Sí",
      no: "No",
      one: "uno",
      two: "dos",
      three: "tres",
      cat: "gato",
      water: "agua",
      mom: "mamá",
    }),
  },
  {
    id: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    translations: t({
      hello: "Bonjour",
      goodbye: "Au revoir",
      thanks: "Merci",
      please: "S'il vous plaît",
      yes: "Oui",
      no: "Non",
      one: "un",
      two: "deux",
      three: "trois",
      cat: "chat",
      water: "eau",
      mom: "maman",
    }),
  },
  {
    id: "de",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    translations: t({
      hello: "Hallo",
      goodbye: "Tschüss",
      thanks: "Danke",
      please: "Bitte",
      yes: "Ja",
      no: "Nein",
      one: "eins",
      two: "zwei",
      three: "drei",
      cat: "Katze",
      water: "Wasser",
      mom: "Mama",
    }),
  },
  {
    id: "it",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    translations: t({
      hello: "Ciao",
      goodbye: "Arrivederci",
      thanks: "Grazie",
      please: "Per favore",
      yes: "Sì",
      no: "No",
      one: "uno",
      two: "due",
      three: "tre",
      cat: "gatto",
      water: "acqua",
      mom: "mamma",
    }),
  },
  {
    id: "pt",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇵🇹",
    translations: t({
      hello: "Olá",
      goodbye: "Tchau",
      thanks: "Obrigado",
      please: "Por favor",
      yes: "Sim",
      no: "Não",
      one: "um",
      two: "dois",
      three: "três",
      cat: "gato",
      water: "água",
      mom: "mãe",
    }),
  },
  {
    id: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    translations: t({
      hello: "Hallo",
      goodbye: "Dag",
      thanks: "Dank je",
      please: "Alsjeblieft",
      yes: "Ja",
      no: "Nee",
      one: "een",
      two: "twee",
      three: "drie",
      cat: "kat",
      water: "water",
      mom: "mama",
    }),
  },
  {
    id: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    flag: "🇹🇷",
    translations: t({
      hello: "Merhaba",
      goodbye: "Hoşça kal",
      thanks: "Teşekkürler",
      please: "Lütfen",
      yes: "Evet",
      no: "Hayır",
      one: "bir",
      two: "iki",
      three: "üç",
      cat: "kedi",
      water: "su",
      mom: "anne",
    }),
  },
  {
    id: "ru",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    scriptHint: "Cyrillic",
    translations: t({
      hello: "Привет",
      goodbye: "Пока",
      thanks: "Спасибо",
      please: "Пожалуйста",
      yes: "Да",
      no: "Нет",
      one: "один",
      two: "два",
      three: "три",
      cat: "кот",
      water: "вода",
      mom: "мама",
    }),
  },
  {
    id: "pl",
    name: "Polish",
    nativeName: "Polski",
    flag: "🇵🇱",
    translations: t({
      hello: "Cześć",
      goodbye: "Do widzenia",
      thanks: "Dziękuję",
      please: "Proszę",
      yes: "Tak",
      no: "Nie",
      one: "jeden",
      two: "dwa",
      three: "trzy",
      cat: "kot",
      water: "woda",
      mom: "mama",
    }),
  },
  {
    id: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    flag: "🇸🇪",
    translations: t({
      hello: "Hej",
      goodbye: "Hej då",
      thanks: "Tack",
      please: "Snälla",
      yes: "Ja",
      no: "Nej",
      one: "ett",
      two: "två",
      three: "tre",
      cat: "katt",
      water: "vatten",
      mom: "mamma",
    }),
  },
  {
    id: "ar",
    name: "Arabic",
    nativeName: "العربية",
    flag: "🇸🇦",
    scriptHint: "Arabic script",
    translations: t({
      hello: "Marhaba",
      goodbye: "Ma'a salama",
      thanks: "Shukran",
      please: "Min fadlak",
      yes: "Na'am",
      no: "La",
      one: "wahid",
      two: "ithnayn",
      three: "thalatha",
      cat: "qitta",
      water: "ma'",
      mom: "umm",
    }),
  },
  {
    id: "zh",
    name: "Chinese",
    nativeName: "中文",
    flag: "🇨🇳",
    scriptHint: "Pinyin",
    translations: t({
      hello: "Nǐ hǎo",
      goodbye: "Zàijiàn",
      thanks: "Xièxiè",
      please: "Qǐng",
      yes: "Shì",
      no: "Bù",
      one: "yī",
      two: "èr",
      three: "sān",
      cat: "māo",
      water: "shuǐ",
      mom: "māma",
    }),
  },
  {
    id: "ja",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    translations: t({
      hello: "Konnichiwa",
      goodbye: "Sayōnara",
      thanks: "Arigatō",
      please: "Onegaishimasu",
      yes: "Hai",
      no: "Iie",
      one: "ichi",
      two: "ni",
      three: "san",
      cat: "neko",
      water: "mizu",
      mom: "okaasan",
    }),
  },
  {
    id: "ko",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    translations: t({
      hello: "Annyeong",
      goodbye: "Annyeonghi gaseyo",
      thanks: "Gamsahamnida",
      please: "Jebal",
      yes: "Ne",
      no: "Ani",
      one: "hana",
      two: "dul",
      three: "set",
      cat: "goyangi",
      water: "mul",
      mom: "eomma",
    }),
  },
  {
    id: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    flag: "🇮🇳",
    translations: t({
      hello: "Namaste",
      goodbye: "Alvida",
      thanks: "Dhanyavād",
      please: "Kripya",
      yes: "Haan",
      no: "Nahin",
      one: "ek",
      two: "do",
      three: "teen",
      cat: "billi",
      water: "pani",
      mom: "maa",
    }),
  },
  {
    id: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    flag: "🇻🇳",
    translations: t({
      hello: "Xin chào",
      goodbye: "Tạm biệt",
      thanks: "Cảm ơn",
      please: "Làm ơn",
      yes: "Có",
      no: "Không",
      one: "một",
      two: "hai",
      three: "ba",
      cat: "mèo",
      water: "nước",
      mom: "mẹ",
    }),
  },
  {
    id: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    flag: "🇮🇩",
    translations: t({
      hello: "Halo",
      goodbye: "Selamat tinggal",
      thanks: "Terima kasih",
      please: "Tolong",
      yes: "Ya",
      no: "Tidak",
      one: "satu",
      two: "dua",
      three: "tiga",
      cat: "kucing",
      water: "air",
      mom: "ibu",
    }),
  },
  {
    id: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
    flag: "🇬🇷",
    translations: t({
      hello: "Yia sou",
      goodbye: "Antio",
      thanks: "Efharistó",
      please: "Parakaló",
      yes: "Né",
      no: "Óchi",
      one: "éna",
      two: "dío",
      three: "tría",
      cat: "gáta",
      water: "neró",
      mom: "mamá",
    }),
  },
  {
    id: "he",
    name: "Hebrew",
    nativeName: "עברית",
    flag: "🇮🇱",
    translations: t({
      hello: "Shalom",
      goodbye: "Lehitraot",
      thanks: "Toda",
      please: "Bevakasha",
      yes: "Ken",
      no: "Lo",
      one: "echad",
      two: "shtayim",
      three: "shalosh",
      cat: "chatul",
      water: "mayim",
      mom: "ima",
    }),
  },
  {
    id: "uk",
    name: "Ukrainian",
    nativeName: "Українська",
    flag: "🇺🇦",
    translations: t({
      hello: "Привіт",
      goodbye: "Бувай",
      thanks: "Дякую",
      please: "Будь ласка",
      yes: "Так",
      no: "Ні",
      one: "один",
      two: "два",
      three: "три",
      cat: "кіт",
      water: "вода",
      mom: "мама",
    }),
  },
  {
    id: "ro",
    name: "Romanian",
    nativeName: "Română",
    flag: "🇷🇴",
    translations: t({
      hello: "Bună",
      goodbye: "La revedere",
      thanks: "Mulțumesc",
      please: "Te rog",
      yes: "Da",
      no: "Nu",
      one: "unu",
      two: "doi",
      three: "trei",
      cat: "pisică",
      water: "apă",
      mom: "mamă",
    }),
  },
  {
    id: "hu",
    name: "Hungarian",
    nativeName: "Magyar",
    flag: "🇭🇺",
    translations: t({
      hello: "Szia",
      goodbye: "Viszlát",
      thanks: "Köszönöm",
      please: "Kérlek",
      yes: "Igen",
      no: "Nem",
      one: "egy",
      two: "kettő",
      three: "három",
      cat: "macska",
      water: "víz",
      mom: "anya",
    }),
  },
  {
    id: "fi",
    name: "Finnish",
    nativeName: "Suomi",
    flag: "🇫🇮",
    translations: t({
      hello: "Hei",
      goodbye: "Näkemiin",
      thanks: "Kiitos",
      please: "Ole hyvä",
      yes: "Kyllä",
      no: "Ei",
      one: "yksi",
      two: "kaksi",
      three: "kolme",
      cat: "kissa",
      water: "vesi",
      mom: "äiti",
    }),
  },
  {
    id: "da",
    name: "Danish",
    nativeName: "Dansk",
    flag: "🇩🇰",
    translations: t({
      hello: "Hej",
      goodbye: "Farvel",
      thanks: "Tak",
      please: "Vær sød",
      yes: "Ja",
      no: "Nej",
      one: "en",
      two: "to",
      three: "tre",
      cat: "kat",
      water: "vand",
      mom: "mor",
    }),
  },
  {
    id: "no",
    name: "Norwegian",
    nativeName: "Norsk",
    flag: "🇳🇴",
    translations: t({
      hello: "Hei",
      goodbye: "Ha det",
      thanks: "Takk",
      please: "Vær så snill",
      yes: "Ja",
      no: "Nei",
      one: "en",
      two: "to",
      three: "tre",
      cat: "katt",
      water: "vann",
      mom: "mamma",
    }),
  },
  {
    id: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    flag: "🇰🇪",
    translations: t({
      hello: "Habari",
      goodbye: "Kwaheri",
      thanks: "Asante",
      please: "Tafadhali",
      yes: "Ndiyo",
      no: "Hapana",
      one: "moja",
      two: "mbili",
      three: "tatu",
      cat: "paka",
      water: "maji",
      mom: "mama",
    }),
  },
  {
    id: "ga",
    name: "Irish",
    nativeName: "Gaeilge",
    flag: "🇮🇪",
    translations: t({
      hello: "Dia dhuit",
      goodbye: "Slán",
      thanks: "Go raibh maith agat",
      please: "Le do thoil",
      yes: "Tá",
      no: "Níl",
      one: "aon",
      two: "dó",
      three: "trí",
      cat: "cat",
      water: "uisce",
      mom: "mam",
    }),
  },
  {
    id: "cy",
    name: "Welsh",
    nativeName: "Cymraeg",
    flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    translations: t({
      hello: "Helo",
      goodbye: "Hwyl fawr",
      thanks: "Diolch",
      please: "Os gwelwch yn dda",
      yes: "Ie",
      no: "Na",
      one: "un",
      two: "dau",
      three: "tri",
      cat: "cath",
      water: "dŵr",
      mom: "mam",
    }),
  },
  {
    id: "cs",
    name: "Czech",
    nativeName: "Čeština",
    flag: "🇨🇿",
    translations: t({
      hello: "Ahoj",
      goodbye: "Na shledanou",
      thanks: "Děkuji",
      please: "Prosím",
      yes: "Ano",
      no: "Ne",
      one: "jedna",
      two: "dva",
      three: "tři",
      cat: "kočka",
      water: "voda",
      mom: "máma",
    }),
  },
].map((lang) => ({
  ...lang,
  translations: mergeTranslations(lang.id, lang.translations) as TranslationMap,
}));

export function getLanguageById(id: string): LanguageDefinition | undefined {
  return LANGUAGES.find((l) => l.id === id);
}

export function searchLanguages(query: string): LanguageDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return LANGUAGES;
  return LANGUAGES.filter(
    (l) =>
      l.name.toLowerCase().includes(q) ||
      l.nativeName.toLowerCase().includes(q) ||
      l.id.includes(q),
  );
}

export function buildWordChoices(
  language: LanguageDefinition,
  phrase: Phrase,
): string[] {
  const correct = language.translations[phrase.id as PhraseId];
  const pool = new Set<string>([correct]);

  for (const p of PHRASES) {
    if (pool.size >= 6) break;
    if (p.id !== phrase.id) pool.add(language.translations[p.id as PhraseId]);
  }

  return shuffle([...pool]);
}

export function pickRandomPhrase(): Phrase {
  return PHRASES[Math.floor(Math.random() * PHRASES.length)];
}

function shuffle<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
