import type { Lesson } from "../lessons-data";

export const LANGUAGE_LESSONS: Lesson[] = [
  {
    id: "lang-vocab-1",
    subjectId: "language",
    ageGroup: "2-4",
    title: "Animals & Their Names",
    description: "Learn animal names",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Animal Words!", content: "Let's learn the names of animals — in English!", character: "girl", visual: "🐾" },
      { type: "teach", title: "Dog", content: "This is a DOG. Dogs bark and love cuddles!", character: "girl", visual: "🐶", voiceText: "This is a dog! Dogs are friendly animals that bark. Can you say DOG?" },
      { type: "teach", title: "Cat", content: "This is a CAT. Cats meow and purr!", character: "girl", visual: "🐱", voiceText: "This is a cat! Cats meow when they want attention. Can you say CAT?" },
      { type: "teach", title: "Bird", content: "This is a BIRD. Birds have wings and can fly!", character: "girl", visual: "🐦", voiceText: "This is a bird! Birds have wings and most of them can fly. Can you say BIRD?" },
      { type: "match", title: "Match the animal!", content: "Match each animal to its name!", pairs: [["🐶", "Dog"], ["🐱", "Cat"], ["🐦", "Bird"], ["🐠", "Fish"]] },
      { type: "quiz", title: "Animal quiz!", content: 'Which animal says "woof"?', options: ["Cat", "Dog", "Bird", "Fish"], correct: 1 },
    ],
  },
  {
    id: "lang-vocab-2",
    subjectId: "language",
    ageGroup: "2-4",
    title: "Food Words",
    description: "Name different foods",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Food Words!", content: "Let's learn the names of yummy foods!", character: "girl", visual: "🍎🍌🥕" },
      { type: "teach", title: "Apple", content: "APPLE — red or green, crunchy and sweet!", character: "girl", visual: "🍎", voiceText: "This is an apple! Apples can be red or green and they're very crunchy. Say APPLE!" },
      { type: "teach", title: "Banana", content: "BANANA — yellow, soft and sweet!", character: "girl", visual: "🍌", voiceText: "This is a banana! Bananas are yellow and soft. Monkeys love them! Say BANANA!" },
      { type: "teach", title: "Carrot", content: "CARROT — orange, crunchy and good for your eyes!", character: "girl", visual: "🥕", voiceText: "This is a carrot! Carrots are orange vegetables. They help keep your eyes healthy! Say CARROT!" },
      { type: "funfact", title: "Fun Fact!", content: "Bananas are slightly radioactive — but don't worry, you'd need to eat 10 million of them for it to be a problem!", visual: "☢️", funFact: 'Strawberries are not actually berries in the botanical sense, but bananas ARE berries. Mind blown!' },
      { type: "quiz", title: "Food quiz!", content: "Which fruit is yellow and curved?", options: ["Apple", "Orange", "Banana", "Mango"], correct: 2 },
    ],
  },
  {
    id: "lang-sentences-1",
    subjectId: "language",
    ageGroup: "4-6",
    title: "Building Sentences",
    description: "Put words together",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Sentences!", content: "A sentence is a group of words that makes complete sense!", character: "girl", visual: "💬" },
      { type: "teach", title: "Subject + Verb", content: 'Every sentence needs WHO does it and WHAT they do: "The dog runs."', character: "girl", visual: "🐕", voiceText: "A sentence needs two things: who or what the sentence is about, and what they do. The dog runs! The girl sings!" },
      { type: "teach", title: "Capital letters", content: "Every sentence starts with a CAPITAL letter and ends with a full stop!", character: "girl", visual: "Aa", voiceText: "Every single sentence must start with a capital letter and end with a full stop. This tells the reader where it starts and ends!" },
      { type: "fillin", title: "Complete the sentence!", content: "The cat ___ on the mat.", blank: "sat", blankOptions: ["ran", "sat", "fly", "big"] },
      { type: "quiz", title: "Sentence quiz!", content: "Which is a correct sentence?", options: ["the dog runs", "The dog runs.", "The dog run.", "dog The runs"], correct: 1 },
    ],
  },
  {
    id: "lang-grammar-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Nouns & Verbs",
    description: "Names of things and action words",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Nouns & Verbs!", content: "Every sentence is built from nouns (things) and verbs (actions)!", character: "girl", visual: "📝" },
      { type: "teach", title: "Nouns", content: "A noun is the name of a person, place or thing. Dog, London, happiness!", character: "girl", visual: "🏷️", voiceText: "A noun is a naming word. Dog, city, book, friendship — these are all nouns. Can you think of three nouns right now?" },
      { type: "teach", title: "Verbs", content: "A verb is an action or doing word. Run, jump, think, love!", character: "girl", visual: "🏃", voiceText: "A verb is a doing word. Run! Jump! Think! Sing! Every sentence must have a verb. What is your favourite action?" },
      { type: "funfact", title: "Fun Fact!", content: 'The most common verb in English is "to be" — I am, you are, they are!', visual: "🌟", funFact: "English has over 170,000 words but most people only use about 20,000 in their everyday speech!" },
      { type: "interact", title: "Noun or verb?", content: 'Is "JUMP" a noun or a verb?', options: ["Noun", "Verb", "Neither", "Both"], correct: 1 },
      { type: "quiz", title: "Grammar quiz!", content: "Which word is a noun?", options: ["Run", "Happy", "Castle", "Quickly"], correct: 2 },
    ],
  },
  {
    id: "lang-grammar-2",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Adjectives",
    description: "Describing words",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Adjectives!", content: "Adjectives are describing words that make writing more interesting!", character: "girl", visual: "🎨" },
      { type: "teach", title: "What is an adjective?", content: 'Adjectives describe nouns. "The BIG dog" — BIG is the adjective!', character: "girl", visual: "🐕", voiceText: "An adjective describes a noun. Instead of just saying dog, say the big fluffy friendly dog! Adjectives paint a picture!" },
      { type: "teach", title: "Adjectives make writing vivid", content: '"A dragon" vs "A fierce, scaly, emerald-green dragon" — which is more exciting?', character: "girl", visual: "🐉", voiceText: "Compare: a dragon appeared. Or: a fierce, enormous, fire-breathing dragon appeared! Which would you rather read?" },
      { type: "experiment", title: "Adjective challenge!", content: "Describe your bedroom using 10 adjectives. How many can you find?", experiment: { title: "Adjective Hunt", materials: ["Paper", "Pencil"], steps: ["Look around your room", "Write down 10 adjectives describing what you see", "Share them with a grown-up — can they guess the room?"] } },
      { type: "fillin", title: "Add the adjective!", content: "The ___ fox ran through the forest.", blank: "quick", blankOptions: ["quick", "run", "forest", "the"] },
      { type: "quiz", title: "Adjective quiz!", content: "Which word is an adjective?", options: ["Slowly", "Jump", "Sparkling", "They"], correct: 2 },
    ],
  },
  {
    id: "lang-storytelling-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Story Writing",
    description: "Beginning, middle and end",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Story Writing!", content: "Every great story has a beginning, middle and end!", character: "girl", visual: "📖" },
      { type: "teach", title: "The Beginning", content: "Introduce the character and the world. Make the reader want to know more!", character: "girl", visual: "🌅", voiceText: "The beginning of a story introduces your character and their world. It should make the reader desperate to find out what happens next!" },
      { type: "teach", title: "The Problem", content: "Something goes wrong! This is what makes the story exciting!", character: "girl", visual: "⚡", voiceText: "Every great story has a problem or challenge. Without a problem there's no adventure! What problem will your character face?" },
      { type: "teach", title: "The Resolution", content: "The character solves the problem — and we see how they've changed!", character: "girl", visual: "🌟", voiceText: "At the end, the character solves the problem. The best endings show how the character has grown or changed from their adventure!" },
      { type: "funfact", title: "Fun Fact!", content: "JK Rowling wrote the first Harry Potter book in a cafe because her flat was too cold to heat!", visual: "☕", funFact: 'The world\'s longest novel is "In Search of Lost Time" by Marcel Proust — it\'s 1.5 million words. Harry Potter is about 1 million words across all 7 books!' },
      { type: "quiz", title: "Story quiz!", content: "What makes a story exciting?", options: ["Long descriptions", "A problem to solve", "Lists of facts", "No characters"], correct: 1 },
    ],
  },
];
