import type { Lesson } from "../lessons-data";

export const MATH_LESSONS: Lesson[] = [
  {
    id: "math-counting-2",
    subjectId: "math",
    ageGroup: "2-4",
    title: "Counting to 10",
    description: "Count all the way to 10!",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Counting to 10!", content: "Let's count higher — all the way to ten!", character: "bear", visual: "🔟", voiceText: "We already know one to five. Now let's go all the way to ten!" },
      { type: "teach", title: "6, 7, 8", content: "Six, seven, eight — hold up fingers as you count!", character: "bear", visual: "6️⃣7️⃣8️⃣", voiceText: "Six! Seven! Eight! How many fingers is that?" },
      { type: "teach", title: "9 and 10!", content: "Nine and TEN — you did it! That's all your fingers!", character: "bear", visual: "9️⃣🔟", voiceText: "Nine and TEN! Hold up all ten fingers — that's ten!" },
      { type: "story", title: "Bear counts honey jars", content: "Bear found honey jars in the forest. Help him count them all — there are 10!", character: "bear", visual: "🍯", voiceText: "Bear found honey jars hidden in the forest! Can you help him count all ten?" },
      { type: "interact", title: "What comes after 7?", content: "Tap the right number!", options: ["6", "8", "9", "10"], correct: 1 },
      { type: "quiz", title: "Count the cookies!", content: "How many cookies?", visual: "🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪", options: ["8", "9", "10", "11"], correct: 2 },
    ],
  },
  {
    id: "math-counting-3",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Counting to 100",
    description: "Skip count by 10s!",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Counting to 100!", content: "We can count in 10s to reach 100 super fast!", character: "bear", visual: "💯", voiceText: "Did you know you can count to 100 really fast by counting in tens?" },
      { type: "teach", title: "Count in 10s", content: "10, 20, 30, 40, 50... clap each time!", character: "bear", visual: "👏", voiceText: "Ten! Twenty! Thirty! Forty! Fifty! Clap each time you say a number!" },
      { type: "teach", title: "Keep going!", content: "60, 70, 80, 90, 100! You made it!", character: "bear", visual: "🎉", voiceText: "Sixty! Seventy! Eighty! Ninety! ONE HUNDRED! Amazing!" },
      { type: "funfact", title: "Fun Fact!", content: "A centipede has 100 legs — one for each number we just counted!", visual: "🐛", funFact: "The word CENT means 100. A century is 100 years. A centimetre is one hundredth of a metre!" },
      { type: "quiz", title: "What comes after 60?", content: "Counting in 10s, what comes next?", options: ["61", "70", "80", "100"], correct: 1 },
    ],
  },
  {
    id: "math-shapes-2",
    subjectId: "math",
    ageGroup: "4-6",
    title: "More Shapes!",
    description: "Rectangles, ovals and more",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "More Shapes!", content: "Beyond circles and squares — let's meet more shapes!", character: "bear", visual: "🟪🟦" },
      { type: "teach", title: "The Rectangle", content: "Like a square but stretched! Doors and books are rectangles.", character: "bear", visual: "▬", voiceText: "A rectangle has four sides but two are longer. Your phone and a door are rectangles!" },
      { type: "teach", title: "The Oval", content: "A stretched circle — like an egg or a rugby ball!", character: "bear", visual: "🥚", voiceText: "An oval is like a circle that has been gently squashed. Eggs and faces are oval!" },
      { type: "match", title: "Match the shape!", content: "Match each shape to its name!", pairs: [["⭕", "Circle"], ["🔺", "Triangle"], ["⬛", "Square"], ["🥚", "Oval"]] },
      { type: "quiz", title: "Shape quiz!", content: "Which shape has 4 sides but they're not all equal?", options: ["Circle", "Square", "Rectangle", "Triangle"], correct: 2 },
    ],
  },
  {
    id: "math-shapes-3",
    subjectId: "math",
    ageGroup: "6-8",
    title: "3D Shapes",
    description: "Spheres, cubes and cylinders",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "3D Shapes!", content: "3D shapes are solid — you can hold them! Think of a ball or a box.", character: "bear", visual: "📦⚽" },
      { type: "teach", title: "The Sphere", content: "A perfectly round 3D shape — like a football or the Earth!", character: "bear", visual: "🌍", voiceText: "A sphere is like a circle but in 3D. You can roll it in any direction. Our planet Earth is a sphere!" },
      { type: "teach", title: "The Cube", content: "6 square faces, 8 corners, 12 edges. Like a dice!", character: "bear", visual: "🎲", voiceText: "A cube has six square faces and they're all exactly the same size. A dice is a cube!" },
      { type: "teach", title: "The Cylinder", content: "Circular top and bottom with a curved side — like a tin of beans!", character: "bear", visual: "🥫", voiceText: "A cylinder has two circular faces and a curved surface. Cans and toilet rolls are cylinders!" },
      { type: "funfact", title: "Fun Fact!", content: "A sphere has no edges or corners — it's the only 3D shape with zero of both!", visual: "🌐", funFact: "Bubbles are always sphere-shaped because that shape uses the least surface for the most volume!" },
      { type: "quiz", title: "3D shapes quiz!", content: "How many faces does a cube have?", options: ["4", "5", "6", "8"], correct: 2 },
    ],
  },
  {
    id: "math-time-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Telling the Time",
    description: "Hours and half hours",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Telling the Time!", content: "Knowing the time helps you know when to eat, sleep and play!", character: "bear", visual: "⏰" },
      { type: "teach", title: "The clock face", content: "A clock has 12 numbers and two hands — short for hours, long for minutes!", character: "bear", visual: "🕐", voiceText: "A clock has a short hand for hours and a long hand for minutes. When the long hand points to 12, it's exactly on the hour!" },
      { type: "teach", title: "O'clock", content: "When the long hand points to 12, it's o'clock — like 3 o'clock!", character: "bear", visual: "🕒", voiceText: "When the long hand is on the 12 and the short hand is on the 3, it's three o'clock!" },
      { type: "teach", title: "Half past", content: "When the long hand points to 6, it's half past!", character: "bear", visual: "🕧", voiceText: "When the long hand points to the 6, half an hour has passed. So half past three means 3:30!" },
      { type: "funfact", title: "Fun Fact!", content: "Before clocks were invented, people told the time by looking at the position of the sun!", visual: "☀️", funFact: "Ancient Egyptians used shadow sticks called sundials to tell the time. No batteries needed!" },
      { type: "interact", title: "What time is it?", content: "The short hand is on 5 and the long hand is on 12. What time is it?", options: ["12 o'clock", "3 o'clock", "5 o'clock", "7 o'clock"], correct: 2 },
      { type: "quiz", title: "Time quiz!", content: 'What does "half past 4" mean?', options: ["4:00", "4:15", "4:30", "4:45"], correct: 2 },
    ],
  },
  {
    id: "math-time-2",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Days, Months & Years",
    description: "Calendars and seasons",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Days & Months!", content: "A year has 12 months, 52 weeks and 365 days — let's learn them!", character: "bear", visual: "📅" },
      { type: "teach", title: "7 days a week", content: "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday!", character: "bear", visual: "📆", voiceText: "There are seven days in a week. Monday to Friday are school days for most people. Saturday and Sunday are the weekend!" },
      { type: "teach", title: "12 months a year", content: "January to December — some have 30 days, some 31, and February has 28!", character: "bear", visual: "🗓️", voiceText: "There are twelve months in a year. January, February, March, April, May, June, July, August, September, October, November, December!" },
      { type: "funfact", title: "Fun Fact!", content: "Every 4 years is a LEAP year — February gets an extra day, making it 29 days!", visual: "🐸", funFact: "If you were born on 29th February, you'd only have a real birthday every 4 years! You'd be called a leapling!" },
      { type: "quiz", title: "Calendar quiz!", content: "How many days are in a week?", options: ["5", "6", "7", "8"], correct: 2 },
    ],
  },
  {
    id: "math-addition-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Adding Numbers",
    description: "Put numbers together",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Adding!", content: "Adding means putting numbers together to make a bigger number!", character: "bear", visual: "➕" },
      { type: "teach", title: "2 + 3 = 5", content: "If you have 2 apples and get 3 more, you have 5 altogether!", character: "bear", visual: "🍎🍎+🍎🍎🍎", voiceText: "Two apples plus three more apples equals five apples altogether. Two plus three equals five!" },
      { type: "story", title: "Bear shares berries", content: "Bear had 4 berries. Fox gave him 3 more. How many does Bear have now?", character: "bear", visual: "🫐", voiceText: "Bear had four berries and Fox gave him three more. Four plus three equals... seven!" },
      { type: "interact", title: "Add them up!", content: "3 + 4 = ?", options: ["5", "6", "7", "8"], correct: 2 },
      { type: "quiz", title: "Addition quiz!", content: "5 + 5 = ?", options: ["8", "9", "10", "11"], correct: 2 },
    ],
  },
  {
    id: "math-subtraction-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Taking Away",
    description: "Subtraction made simple",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Taking Away!", content: "Subtraction means taking numbers away to get a smaller number!", character: "bear", visual: "➖" },
      { type: "teach", title: "5 - 2 = 3", content: "If you have 5 cookies and eat 2, you have 3 left!", character: "bear", visual: "🍪", voiceText: "Five cookies take away two cookies leaves three cookies. Five minus two equals three!" },
      { type: "experiment", title: "Try it at home!", content: "Use 10 small objects like coins or buttons. Take some away and count what's left!", experiment: { title: "Subtraction with Objects", materials: ["10 small objects (coins, buttons, grapes)"], steps: ["Line up 10 objects", "Take away 3 of them", "Count how many are left", "Try different numbers!"] } },
      { type: "interact", title: "Take away!", content: "8 - 3 = ?", options: ["4", "5", "6", "7"], correct: 1 },
      { type: "quiz", title: "Subtraction quiz!", content: "10 - 4 = ?", options: ["5", "6", "7", "8"], correct: 1 },
    ],
  },
  {
    id: "math-multiply-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Multiplication",
    description: "Fast repeated adding",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Multiplication!", content: "Multiplication is just fast adding of the same number!", character: "bear", visual: "✖️" },
      { type: "teach", title: "3 × 2 = 6", content: "3 groups of 2 is the same as 2+2+2 = 6!", character: "bear", visual: "🟡🟡 🟡🟡 🟡🟡", voiceText: "Three times two means three groups of two. Two plus two plus two equals six. Three times two equals six!" },
      { type: "teach", title: "The times table trick", content: "Anything times 10 just adds a zero — 5×10=50, 7×10=70!", character: "bear", visual: "🔟", voiceText: "Here's a brilliant trick. Any number times ten just gets a zero added! Four times ten is forty. Nine times ten is ninety!" },
      { type: "funfact", title: "Fun Fact!", content: 'The word "multiply" comes from Latin meaning "many folds" — like folding paper to make it thicker!', visual: "📄", funFact: "If you fold a piece of paper 42 times it would reach from the Earth to the Moon — that's multiplication in action!" },
      { type: "interact", title: "Multiply!", content: "4 × 3 = ?", options: ["10", "11", "12", "13"], correct: 2 },
      { type: "quiz", title: "Times tables!", content: "5 × 5 = ?", options: ["20", "25", "30", "35"], correct: 1 },
    ],
  },
  {
    id: "math-money-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Money & Coins",
    description: "Counting money",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Money!", content: "Money helps us buy things we need. Let's learn about coins!", character: "bear", visual: "💰" },
      { type: "teach", title: "Pennies and pounds", content: "100 pennies make 1 pound. Coins come in 1p, 2p, 5p, 10p, 20p, 50p, £1 and £2!", character: "bear", visual: "🪙", voiceText: "There are one hundred pennies in one pound. Coins come in lots of different values!" },
      { type: "story", title: "Bear buys honey", content: "Bear has 20p. A jar of honey costs 15p. How much change does he get?", character: "bear", visual: "🍯", voiceText: "Bear has twenty pence and honey costs fifteen pence. Twenty minus fifteen equals five pence change!" },
      { type: "experiment", title: "Try at home!", content: "Ask a grown-up to show you real coins. Can you find coins that add up to exactly 50p?", experiment: { title: "Coin Hunt", materials: ["Real coins from your piggy bank or a grown-up"], steps: ["Spread out all the coins", "Sort them by size", "Try to make exactly 50p in different ways", "Which way uses the fewest coins?"] } },
      { type: "quiz", title: "Money quiz!", content: "How many 10p coins make £1?", options: ["5", "8", "10", "12"], correct: 2 },
    ],
  },
  {
    id: "math-fractions-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Fractions",
    description: "Halves, quarters and thirds",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Fractions!", content: "A fraction is a part of a whole. Like half a pizza or a quarter of an apple!", character: "bear", visual: "🍕" },
      { type: "teach", title: "One half (½)", content: "Split something into 2 EQUAL parts — each part is one half!", character: "bear", visual: "½", voiceText: "A half means splitting something into two equal pieces. If you share a sandwich with one friend, you each get one half!" },
      { type: "teach", title: "One quarter (¼)", content: "Split into 4 EQUAL parts — each part is one quarter!", character: "bear", visual: "¼", voiceText: "A quarter means splitting into four equal pieces. Fold a piece of paper in half then in half again — each piece is a quarter!" },
      { type: "experiment", title: "Fraction pizza!", content: "Draw a circle and cut it into equal slices to make fraction pizza!", experiment: { title: "Paper Pizza Fractions", materials: ["Paper", "Pencil", "Scissors"], steps: ["Draw a big circle (your pizza)", "Fold it in half — that's 2 halves", "Fold again — that's 4 quarters", "Can you fold it into 8 eighths?"] } },
      { type: "funfact", title: "Fun Fact!", content: 'The word "fraction" comes from the Latin word "fractus" meaning broken!', visual: "💥", funFact: "The line between the top and bottom numbers of a fraction is called a vinculum. The top number is the numerator and the bottom is the denominator!" },
      { type: "quiz", title: "Fractions quiz!", content: "A pizza is cut into 4 equal slices. You eat 1 slice. What fraction did you eat?", options: ["½", "¼", "⅓", "¾"], correct: 1 },
    ],
  },
];
