import type { Lesson } from "../lessons-data";

export const SCIENCE_LESSONS: Lesson[] = [
  {
    id: "science-plants-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "How Plants Grow",
    description: "Seeds, roots and photosynthesis",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Plants!", content: "Plants are alive! They eat, grow, breathe and make babies just like animals!", character: "owl", visual: "🌱" },
      { type: "teach", title: "From seed to plant", content: "A seed contains everything needed to grow. Water + warmth + soil = life!", character: "owl", visual: "🌱", voiceText: "A tiny seed contains all the instructions to grow into a giant tree! Add water, warmth and soil and the magic begins!" },
      { type: "teach", title: "Photosynthesis", content: "Plants use sunlight to make food from air and water — this is called photosynthesis!", character: "owl", visual: "☀️🌿", voiceText: "Plants are amazing because they make their own food! They take water from the soil, carbon dioxide from the air, and use sunlight to make sugar. This is called photosynthesis!" },
      { type: "experiment", title: "Grow your own!", content: "Grow a bean plant in a clear cup to watch the roots!", experiment: { title: "Bean in a Cup", materials: ["A clear plastic cup", "Kitchen paper", "A bean seed", "Water"], steps: ["Scrunch kitchen paper and put it in the cup", "Push a bean seed between the paper and the cup wall", "Add a little water to keep paper damp", "Put near a window", "Watch the root and shoot appear over a week!"] } },
      { type: "funfact", title: "Fun Fact!", content: "The oldest tree in the world is a bristlecone pine called Methuselah — it's over 4,800 years old!", visual: "🌳", funFact: 'Trees communicate with each other through underground fungal networks — scientists call it the "Wood Wide Web"!' },
      { type: "quiz", title: "Plants quiz!", content: "What do plants use to make food?", options: ["Moonlight + soil", "Sunlight + water + air", "Rain + darkness", "Wind + rocks"], correct: 1 },
    ],
  },
  {
    id: "science-human-body-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "The Human Body",
    description: "Bones, muscles and organs",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Your Amazing Body!", content: "Your body is the most incredible machine ever made. Let's explore it!", character: "owl", visual: "🫀" },
      { type: "teach", title: "Your skeleton", content: "You have 206 bones! They protect your organs and help you move!", character: "owl", visual: "🦴", voiceText: "Your skeleton has 206 bones. They hold you up, protect your soft organs and work with your muscles to help you move!" },
      { type: "teach", title: "Your heart", content: "Your heart beats about 100,000 times every single day!", character: "owl", visual: "❤️", voiceText: "Your heart is about the size of your fist and it beats one hundred thousand times every day, pumping blood around your entire body!" },
      { type: "experiment", title: "Feel your heartbeat!", content: "Put your hand on your chest. Now jump 20 times and feel how fast it goes!", experiment: { title: "Heartbeat Science", materials: ["Your hand", "A timer (optional)"], steps: ["Place your hand on your chest", "Count your heartbeats for 10 seconds", "Multiply by 6 to get beats per minute", "Now do 20 star jumps", "Count again — how much faster is it?"] } },
      { type: "funfact", title: "Fun Fact!", content: "Babies are born with 300 bones but adults only have 206 — they fuse together as you grow!", visual: "👶", funFact: "Your femur (thigh bone) is the strongest bone in your body and can support 30 times your body weight!" },
      { type: "quiz", title: "Body quiz!", content: "How many bones does an adult human have?", options: ["106", "206", "306", "406"], correct: 1 },
    ],
  },
  {
    id: "science-space-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Our Solar System",
    description: "The Sun, planets and space",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Space!", content: "Our solar system has 8 planets all orbiting the Sun — let's explore!", character: "owl", visual: "🚀" },
      { type: "teach", title: "The Sun", content: "The Sun is a star — a giant ball of burning gas so big a million Earths could fit inside!", character: "owl", visual: "☀️", voiceText: "The Sun is our closest star and it's enormous! One million planet Earths could fit inside it. Without the Sun there would be no life on Earth!" },
      { type: "teach", title: "The 8 planets", content: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune — in order from the Sun!", character: "owl", visual: "🪐", voiceText: "My Very Educated Mother Just Served Us Nachos — that's how to remember the planets in order! Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune!" },
      { type: "funfact", title: "Fun Fact!", content: "A day on Venus is longer than a year on Venus — it spins so slowly!", visual: "🌟", funFact: "If you could fly to the Moon in a plane it would take about 20 days. To reach the Sun would take 20 years. To reach the nearest star would take 5 million years!" },
      { type: "interact", title: "Which planet?", content: "Which planet has the most beautiful rings?", options: ["Jupiter", "Mars", "Saturn", "Uranus"], correct: 2 },
      { type: "quiz", title: "Space quiz!", content: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correct: 1 },
    ],
  },
  {
    id: "science-habitats-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Animal Habitats",
    description: "Where animals live",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Animal Homes!", content: "Every animal has a special home called a habitat!", character: "owl", visual: "🌍" },
      { type: "teach", title: "Ocean habitat", content: "The ocean is the biggest habitat — home to whales, fish and coral!", character: "owl", visual: "🌊🐳", voiceText: "The ocean covers 70 percent of Earth and is home to the most animals of any habitat. Even the deepest parts have life!" },
      { type: "teach", title: "Rainforest habitat", content: "Rainforests have more species than anywhere else — they're the Earth's lungs!", character: "owl", visual: "🌴🦜", voiceText: "Rainforests cover only 6 percent of Earth but contain over half of all plant and animal species. They produce 20 percent of our oxygen!" },
      { type: "funfact", title: "Fun Fact!", content: "The deep ocean is so unexplored that we know more about the surface of Mars than the ocean floor!", visual: "🌌", funFact: "There are animals in the deep ocean that make their own light — it's called bioluminescence! Anglerfish, jellyfish and even some sharks can glow!" },
      { type: "experiment", title: "Habitat in a bottle!", content: "Make a mini rainforest habitat in a glass bottle!", experiment: { title: "Mini Terrarium", materials: ["Clear glass or plastic bottle", "Small stones", "Soil", "Small plant or grass seeds", "Water"], steps: ["Add a layer of stones to the bottom", "Add soil on top", "Plant seeds or a small plant", "Add a little water", "Seal the top and watch your mini habitat grow!"] } },
      { type: "quiz", title: "Habitat quiz!", content: "Where do polar bears live?", options: ["Rainforest", "Desert", "Arctic", "Ocean"], correct: 2 },
    ],
  },
];
