import type { Lesson } from "../lessons-data";

/** Extra lessons to grow the library toward 15–20 per subject */
export const SUPPLEMENT_LESSONS: Lesson[] = [
  // ── MATH (8 more → ~21 with core 2 + math 11) ──
  {
    id: "math-compare-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Bigger & Smaller",
    description: "Compare numbers",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Compare!", content: "Which number is bigger? Which is smaller?", character: "bear", visual: "⚖️" },
      { type: "teach", title: "More than", content: "8 is MORE than 5. The bigger number wins!", character: "bear", visual: "8️⃣5️⃣" },
      { type: "teach", title: "Less than", content: "3 is LESS than 7. The smaller number is on the left!", character: "bear", visual: "3️⃣7️⃣" },
      { type: "funfact", title: "Fun Fact!", content: "Zero was invented in India over 1,500 years ago!", visual: "0️⃣", funFact: "Before zero, people had trouble writing numbers like 205 — they couldn't show an empty tens place!" },
      { type: "interact", title: "Which is bigger?", content: "Tap the bigger number!", options: ["4", "9", "6", "2"], correct: 1 },
      { type: "quiz", title: "Compare quiz!", content: "Which is smaller: 12 or 8?", options: ["12", "8", "Same", "Neither"], correct: 1 },
    ],
  },
  {
    id: "math-patterns-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "Number Patterns",
    description: "What comes next?",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Patterns!", content: "Numbers can follow a pattern — can you spot it?", character: "bear", visual: "🔁" },
      { type: "teach", title: "Counting on", content: "2, 4, 6, 8 — we add 2 each time!", character: "bear", visual: "2️⃣4️⃣6️⃣8️⃣" },
      { type: "teach", title: "Odd and even", content: "Even numbers end in 0, 2, 4, 6, 8. Odd numbers end in 1, 3, 5, 7, 9!", character: "bear", visual: "🔢" },
      { type: "interact", title: "What comes next?", content: "1, 3, 5, 7, ?", options: ["6", "8", "9", "10"], correct: 2 },
      { type: "quiz", title: "Pattern quiz!", content: "2, 4, 6, 8, ?", options: ["9", "10", "11", "12"], correct: 1 },
    ],
  },
  {
    id: "math-measure-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Measuring Length",
    description: "Metres and centimetres",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Measuring!", content: "We measure how long things are using metres and centimetres!", character: "bear", visual: "📏" },
      { type: "teach", title: "Centimetres", content: "A centimetre is tiny — about the width of your little finger!", character: "bear", visual: "📐" },
      { type: "teach", title: "Metres", content: "100 centimetres make 1 metre — about one big step!", character: "bear", visual: "👣" },
      { type: "experiment", title: "Measure at home!", content: "Use a ruler or tape to measure 5 things in your room!", experiment: { title: "Room Measure Hunt", materials: ["Ruler or tape measure", "Paper", "Pencil"], steps: ["Pick 5 objects", "Measure each in cm", "Write them down", "Which is longest?"] } },
      { type: "quiz", title: "Measure quiz!", content: "How many cm in 1 metre?", options: ["10", "50", "100", "1000"], correct: 2 },
    ],
  },
  {
    id: "math-data-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Charts & Graphs",
    description: "Reading simple data",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Graphs!", content: "Graphs show information in a picture — easy to understand!", character: "bear", visual: "📊" },
      { type: "teach", title: "Bar charts", content: "Taller bars mean more. Shorter bars mean less!", character: "bear", visual: "📶" },
      { type: "funfact", title: "Fun Fact!", content: "The first pie chart was drawn in 1801 by William Playfair!", visual: "🥧", funFact: "Florence Nightingale used a special chart called a polar area diagram to show how soldiers died in the Crimean War!" },
      { type: "interact", title: "Read the chart!", content: "Red bar is tallest. Which colour has the MOST?", options: ["Blue", "Green", "Red", "Yellow"], correct: 2 },
      { type: "quiz", title: "Graph quiz!", content: "What do taller bars usually mean?", options: ["Less", "More", "Nothing", "Broken"], correct: 1 },
    ],
  },
  {
    id: "math-division-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Sharing Equally",
    description: "Introduction to division",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Sharing!", content: "Division means sharing equally into groups!", character: "bear", visual: "➗" },
      { type: "teach", title: "12 ÷ 3 = 4", content: "12 sweets shared between 3 friends — each gets 4!", character: "bear", visual: "🍬" },
      { type: "story", title: "Bear shares biscuits", content: "8 biscuits, 2 friends. Each friend gets 4 biscuits!", character: "bear", visual: "🍪" },
      { type: "interact", title: "Share!", content: "10 ÷ 2 = ?", options: ["3", "4", "5", "6"], correct: 2 },
      { type: "quiz", title: "Division quiz!", content: "15 ÷ 3 = ?", options: ["3", "4", "5", "6"], correct: 2 },
    ],
  },
  {
    id: "math-ordinal-1",
    subjectId: "math",
    ageGroup: "4-6",
    title: "First, Second, Third",
    description: "Ordinal numbers",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Order words!", content: "1st, 2nd, 3rd tell us position in a race!", character: "bear", visual: "🏁" },
      { type: "teach", title: "First place", content: "The winner is FIRST — number one!", character: "bear", visual: "🥇" },
      { type: "teach", title: "Second and third", content: "Second is next, then third!", character: "bear", visual: "🥈🥉" },
      { type: "interact", title: "What place?", content: "You came after 1st but before 3rd. You are...", options: ["1st", "2nd", "3rd", "4th"], correct: 1 },
      { type: "quiz", title: "Ordinal quiz!", content: "4th means you are in position...", options: ["Three", "Four", "Five", "Six"], correct: 1 },
    ],
  },
  {
    id: "math-symmetry-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Symmetry",
    description: "Mirror images",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Symmetry!", content: "Some shapes look the same on both sides — that's symmetry!", character: "bear", visual: "🦋" },
      { type: "teach", title: "Line of symmetry", content: "Fold a butterfly — both wings match perfectly!", character: "bear", visual: "🪞" },
      { type: "funfact", title: "Fun Fact!", content: "Snowflakes always have 6-fold symmetry — no two are exactly alike!", visual: "❄️", funFact: "A single snowflake can have up to 200 ice crystals, all arranged symmetrically!" },
      { type: "interact", title: "Symmetrical?", content: "Which shape has a line of symmetry?", options: ["Scribble", "Circle", "Random blob", "Broken line"], correct: 1 },
      { type: "quiz", title: "Symmetry quiz!", content: "A square has how many lines of symmetry?", options: ["2", "3", "4", "6"], correct: 2 },
    ],
  },
  {
    id: "math-place-value-1",
    subjectId: "math",
    ageGroup: "6-8",
    title: "Place Value",
    description: "Tens and ones",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Place value!", content: "In 47, the 4 means 40 and the 7 means 7!", character: "bear", visual: "47" },
      { type: "teach", title: "Tens and ones", content: "The left digit is tens, the right is ones!", character: "bear", visual: "🔟1️⃣" },
      { type: "teach", title: "Hundreds", content: "In 382, 3 is hundreds, 8 is tens, 2 is ones!", character: "bear", visual: "💯" },
      { type: "fillin", title: "Build the number!", content: "3 tens and 5 ones = ___", blank: "35", blankOptions: ["53", "35", "30", "8"] },
      { type: "quiz", title: "Place value quiz!", content: "In 56, what does the 5 represent?", options: ["5", "50", "500", "56"], correct: 1 },
    ],
  },
  // ── LANGUAGE (14 more) ──
  {
    id: "lang-rhymes-1",
    subjectId: "language",
    ageGroup: "2-4",
    title: "Rhyming Words",
    description: "Words that sound alike",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Rhymes!", content: "Cat and hat rhyme — they end the same!", character: "girl", visual: "🎵" },
      { type: "teach", title: "Cat / Hat", content: "Listen: cat, hat, bat — they all rhyme!", character: "girl", visual: "🐱🎩" },
      { type: "teach", title: "Sun / Fun", content: "Sun and fun rhyme too!", character: "girl", visual: "☀️" },
      { type: "match", title: "Match rhymes!", content: "Match words that rhyme!", pairs: [["Cat", "Hat"], ["Sun", "Fun"], ["Dog", "Log"], ["Bee", "Tree"]] },
      { type: "quiz", title: "Rhyme quiz!", content: "Which rhymes with moon?", options: ["Sun", "Spoon", "Star", "Sky"], correct: 1 },
    ],
  },
  {
    id: "lang-opposites-1",
    subjectId: "language",
    ageGroup: "2-4",
    title: "Opposites",
    description: "Big and small, hot and cold",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Opposites!", content: "Opposites mean the opposite thing!", character: "girl", visual: "↔️" },
      { type: "teach", title: "Big / Small", content: "An elephant is BIG. A mouse is SMALL.", character: "girl", visual: "🐘🐭" },
      { type: "teach", title: "Hot / Cold", content: "Fire is HOT. Ice is COLD.", character: "girl", visual: "🔥🧊" },
      { type: "match", title: "Match opposites!", content: "Match each word to its opposite!", pairs: [["Hot", "Cold"], ["Up", "Down"], ["Day", "Night"], ["Happy", "Sad"]] },
      { type: "quiz", title: "Opposite quiz!", content: "What is the opposite of fast?", options: ["Quick", "Slow", "Run", "Zoom"], correct: 1 },
    ],
  },
  {
    id: "lang-questions-1",
    subjectId: "language",
    ageGroup: "4-6",
    title: "Asking Questions",
    description: "Who, what, where, when",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Questions!", content: "Questions help us learn. They often start with special words!", character: "girl", visual: "❓" },
      { type: "teach", title: "Who?", content: "WHO asks about a person. Who ate the cake?", character: "girl", visual: "👤" },
      { type: "teach", title: "What? Where?", content: "WHAT asks about a thing. WHERE asks about a place!", character: "girl", visual: "📍" },
      { type: "fillin", title: "Pick the word!", content: "___ is your name?", blank: "What", blankOptions: ["What", "Where", "When", "Why"] },
      { type: "quiz", title: "Question quiz!", content: "Which word starts a question about place?", options: ["Who", "What", "Where", "How"], correct: 2 },
    ],
  },
  {
    id: "lang-punctuation-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Punctuation",
    description: "Full stops, commas and more",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Punctuation!", content: "Punctuation marks tell us how to read sentences!", character: "girl", visual: ".,!?" },
      { type: "teach", title: "Full stop", content: "A full stop ends a sentence.", character: "girl", visual: "." },
      { type: "teach", title: "Question mark", content: "A question mark ends a question!", character: "girl", visual: "?" },
      { type: "funfact", title: "Fun Fact!", content: "The @ symbol is called an at sign and is over 500 years old!", visual: "@", funFact: "The exclamation mark comes from the Latin word for joy — io — written vertically!" },
      { type: "quiz", title: "Punctuation quiz!", content: "Which ends a question?", options: [".", ",", "!", "?"], correct: 3 },
    ],
  },
  {
    id: "lang-synonyms-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Synonyms",
    description: "Words with similar meanings",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Synonyms!", content: "Happy and joyful mean almost the same — they're synonyms!", character: "girl", visual: "📚" },
      { type: "teach", title: "Big / Large", content: "Big and large are synonyms!", character: "girl", visual: "🐘" },
      { type: "match", title: "Match synonyms!", content: "Match words with similar meanings!", pairs: [["Happy", "Joyful"], ["Small", "Tiny"], ["Fast", "Quick"], ["Smart", "Clever"]] },
      { type: "quiz", title: "Synonym quiz!", content: "A synonym for sad is...", options: ["Happy", "Unhappy", "Tall", "Run"], correct: 1 },
    ],
  },
  {
    id: "lang-homophones-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Homophones",
    description: "Words that sound the same",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Homophones!", content: "Sea and see sound the same but mean different things!", character: "girl", visual: "👂" },
      { type: "teach", title: "There / Their / They're", content: "Three words, same sound, different spellings!", character: "girl", visual: "✏️" },
      { type: "funfact", title: "Fun Fact!", content: 'English has more homophones than almost any language because of its mixed history!', visual: "🌍", funFact: 'The word "set" has over 400 meanings in the dictionary — the most of any English word!' },
      { type: "interact", title: "Which spelling?", content: "I can ___ the sea. (able to view)", options: ["sea", "see", "cee", "si"], correct: 1 },
      { type: "quiz", title: "Homophone quiz!", content: "A bear is an animal. Bare means...", options: ["Furry", "Empty/naked", "Colour", "Food"], correct: 1 },
    ],
  },
  {
    id: "lang-compound-1",
    subjectId: "language",
    ageGroup: "4-6",
    title: "Compound Words",
    description: "Two words become one",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Compound words!", content: "Sun + flower = sunflower! Two words join together!", character: "girl", visual: "🌻" },
      { type: "teach", title: "Rainbow", content: "Rain + bow = rainbow!", character: "girl", visual: "🌈" },
      { type: "teach", title: "Butterfly", content: "Butter + fly = butterfly! (It is not made of butter!)", character: "girl", visual: "🦋" },
      { type: "match", title: "Build compounds!", content: "Match the two parts!", pairs: [["Sun", "flower"], ["Rain", "bow"], ["Star", "fish"], ["Foot", "ball"]] },
      { type: "quiz", title: "Compound quiz!", content: "Which is a compound word?", options: ["Cat", "Sunflower", "Run", "Big"], correct: 1 },
    ],
  },
  {
    id: "lang-prefixes-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Prefixes",
    description: "Word beginnings that change meaning",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Prefixes!", content: "Un- means not. Unhappy means not happy!", character: "girl", visual: "🔤" },
      { type: "teach", title: "Re- means again", content: "Redo means do again. Rewrite means write again!", character: "girl", visual: "🔁" },
      { type: "teach", title: "Pre- means before", content: "Preview means view before!", character: "girl", visual: "⏮️" },
      { type: "fillin", title: "Un- means not!", content: "___kind means not kind.", blank: "Un", blankOptions: ["Re", "Pre", "Un", "Dis"] },
      { type: "quiz", title: "Prefix quiz!", content: "What does re- usually mean?", options: ["Not", "Again", "Before", "After"], correct: 1 },
    ],
  },
  {
    id: "lang-idioms-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Fun Idioms",
    description: "Phrases that mean something else",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Idioms!", content: '"It\'s raining cats and dogs" means heavy rain — not real animals!', character: "girl", visual: "🌧️" },
      { type: "teach", title: "Piece of cake", content: "Means something is very easy!", character: "girl", visual: "🍰" },
      { type: "teach", title: "Break a leg", content: "Means good luck — especially before a show!", character: "girl", visual: "🎭" },
      { type: "funfact", title: "Fun Fact!", content: "English has over 25,000 idioms!", visual: "💬", funFact: '"Bite the bullet" comes from soldiers biting bullets during surgery before anaesthetic!' },
      { type: "quiz", title: "Idiom quiz!", content: '"Piece of cake" means...', options: ["Yummy dessert", "Very easy", "Birthday", "Baking"], correct: 1 },
    ],
  },
  {
    id: "lang-reading-1",
    subjectId: "language",
    ageGroup: "4-6",
    title: "Reading Clues",
    description: "Pictures and context help",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Reading clues!", content: "Pictures and the rest of the sentence help you guess tricky words!", character: "girl", visual: "📖" },
      { type: "teach", title: "Picture clues", content: "If you see a picture of a dog, the word might be dog!", character: "girl", visual: "🐶" },
      { type: "story", title: "The lost puppy", content: "The story shows a puppy in a park. Even if a word is hard, the picture helps!", character: "girl", visual: "🐕" },
      { type: "interact", title: "Guess the word!", content: "The animal says moo. It is a...", options: ["Cat", "Cow", "Bird", "Fish"], correct: 1 },
      { type: "quiz", title: "Reading quiz!", content: "Context clues help you...", options: ["Skip reading", "Guess word meaning", "Draw pictures", "Sleep"], correct: 1 },
    ],
  },
  {
    id: "lang-commands-1",
    subjectId: "language",
    ageGroup: "4-6",
    title: "Commands & Instructions",
    description: "Bossy verbs",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Commands!", content: "Sit down! Stand up! These tell someone what to do!", character: "girl", visual: "📢" },
      { type: "teach", title: "Bossy verbs", content: "Commands often start with a verb: Run! Stop! Listen!", character: "girl", visual: "🏃" },
      { type: "experiment", title: "Follow instructions!", content: "Write 5 commands for a grown-up to follow!", experiment: { title: "Command Course", materials: ["Paper", "Pencil", "Space to move"], steps: ["Write 5 commands", "Read them to a grown-up", "They must follow exactly", "Did any command confuse them?"] } },
      { type: "quiz", title: "Command quiz!", content: "Which is a command?", options: ["The sky is blue.", "Please close the door.", "I like pizza.", "Cats are soft."], correct: 1 },
    ],
  },
  {
    id: "lang-alliteration-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Alliteration",
    description: "Same sound at the start",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Alliteration!", content: "Peter Piper picked — the P sound repeats!", character: "girl", visual: "🔊" },
      { type: "teach", title: "Silly Sally", content: "Silly Sally sang songs — lots of S sounds!", character: "girl", visual: "🎤" },
      { type: "teach", title: "Make your own", content: "Try: Happy Harry has a hat!", character: "girl", visual: "🎩" },
      { type: "interact", title: "Spot alliteration!", content: "Which phrase uses alliteration?", options: ["Big brown bear", "The cat sat", "I went home", "Sun is hot"], correct: 0 },
      { type: "quiz", title: "Alliteration quiz!", content: "Alliteration repeats the...", options: ["End sound", "Start sound", "Middle", "No sounds"], correct: 1 },
    ],
  },
  {
    id: "lang-onomatopoeia-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Sound Words",
    description: "Buzz, crash, splash!",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Sound words!", content: "Buzz! Crash! Pop! Words that sound like what they describe!", character: "girl", visual: "💥" },
      { type: "teach", title: "Animal sounds", content: "Moo, woof, meow — onomatopoeia!", character: "girl", visual: "🐄" },
      { type: "funfact", title: "Fun Fact!", content: "Different languages use different sounds for the same animal!", visual: "🌍", funFact: "In Japanese a dog says wan-wan, not woof! In French a pig says groin-groin!" },
      { type: "match", title: "Match the sound!", content: "Match the sound to the thing!", pairs: [["Buzz", "Bee"], ["Splash", "Water"], ["Crash", "Thunder"], ["Tick", "Clock"]] },
      { type: "quiz", title: "Sound quiz!", content: "Which is an onomatopoeia?", options: ["Happy", "Splash", "Chair", "Quickly"], correct: 1 },
    ],
  },
  {
    id: "lang-dialogue-1",
    subjectId: "language",
    ageGroup: "6-8",
    title: "Writing Dialogue",
    description: "Speech in stories",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Dialogue!", content: "When characters speak in stories we use speech marks!", character: "girl", visual: '💬"' },
      { type: "teach", title: "Speech marks", content: '"Hello!" said Bear. The words inside marks are spoken aloud.', character: "girl", visual: "🐻" },
      { type: "teach", title: "New line for new speaker", content: "Each new speaker starts on a new line!", character: "girl", visual: "📝" },
      { type: "fillin", title: "Punctuate!", content: '"I love honey" ___ Bear.', blank: "said", blankOptions: ["said", "Said", "say", "says"] },
      { type: "quiz", title: "Dialogue quiz!", content: "Speech marks show...", options: ["Whispers", "Spoken words", "Titles", "Endings"], correct: 1 },
    ],
  },
  // ── ALPHABET (12 more) ──
  {
    id: "alpha-ghi-1",
    subjectId: "alphabet",
    ageGroup: "2-4",
    title: "Letters G, H, I",
    description: "Three more letters",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "G, H, I!", content: "Three more letters today!", character: "boy", visual: "GHI" },
      { type: "teach", title: "G is for Goat", content: "G makes a GUH sound!", character: "boy", visual: "🐐" },
      { type: "teach", title: "H is for Hat", content: "H makes a breathy HHH sound!", character: "boy", visual: "🎩" },
      { type: "teach", title: "I is for Igloo", content: "I makes an IH sound!", character: "boy", visual: "🏠" },
      { type: "quiz", title: "Letter quiz!", content: "Goat starts with...", options: ["H", "G", "I", "J"], correct: 1 },
    ],
  },
  {
    id: "alpha-jkl-1",
    subjectId: "alphabet",
    ageGroup: "2-4",
    title: "Letters J, K, L",
    description: "Three more letters",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "J, K, L!", content: "Keep learning the alphabet!", character: "boy", visual: "JKL" },
      { type: "teach", title: "J is for Jelly", content: "J makes a JUH sound!", character: "boy", visual: "🍮" },
      { type: "teach", title: "K is for Kite", content: "K makes a KUH sound!", character: "boy", visual: "🪁" },
      { type: "teach", title: "L is for Lion", content: "L makes an LLL sound!", character: "boy", visual: "🦁" },
      { type: "interact", title: "Kite starts with...", content: "Which letter?", options: ["J", "L", "K", "M"], correct: 2 },
    ],
  },
  {
    id: "alpha-mno-1",
    subjectId: "alphabet",
    ageGroup: "2-4",
    title: "Letters M, N, O",
    description: "Middle of the alphabet",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "M, N, O!", content: "Halfway through the alphabet!", character: "boy", visual: "MNO" },
      { type: "teach", title: "M is for Moon", content: "M makes MMM!", character: "boy", visual: "🌙" },
      { type: "teach", title: "N is for Nest", content: "N makes NNN!", character: "boy", visual: "🪺" },
      { type: "teach", title: "O is for Orange", content: "O makes OH!", character: "boy", visual: "🍊" },
      { type: "quiz", title: "Quiz!", content: "Moon starts with...", options: ["N", "O", "M", "P"], correct: 2 },
    ],
  },
  {
    id: "alpha-pqr-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Letters P, Q, R",
    description: "Three more letters",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "P, Q, R!", content: "Almost done with the alphabet!", character: "boy", visual: "PQR" },
      { type: "teach", title: "P is for Penguin", content: "P makes PUH!", character: "boy", visual: "🐧" },
      { type: "teach", title: "Q is for Queen", content: "Q almost always has U after it — QU!", character: "boy", visual: "👑" },
      { type: "teach", title: "R is for Rainbow", content: "R makes RRR!", character: "boy", visual: "🌈" },
      { type: "quiz", title: "Quiz!", content: "Queen starts with...", options: ["P", "R", "Q", "S"], correct: 2 },
    ],
  },
  {
    id: "alpha-stu-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Letters S, T, U",
    description: "Three more letters",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "S, T, U!", content: "So close to the end!", character: "boy", visual: "STU" },
      { type: "teach", title: "S is for Sun", content: "S makes SSS like a snake!", character: "boy", visual: "☀️" },
      { type: "teach", title: "T is for Tree", content: "T makes TTT!", character: "boy", visual: "🌳" },
      { type: "teach", title: "U is for Umbrella", content: "U makes UH!", character: "boy", visual: "☂️" },
      { type: "interact", title: "Sun starts with...", content: "Tap the letter!", options: ["T", "S", "U", "V"], correct: 1 },
    ],
  },
  {
    id: "alpha-vwx-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Letters V, W, X",
    description: "Three more letters",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "V, W, X!", content: "Nearly at Z!", character: "boy", visual: "VWX" },
      { type: "teach", title: "V is for Violin", content: "V makes VVV!", character: "boy", visual: "🎻" },
      { type: "teach", title: "W is for Whale", content: "W sounds like WUH!", character: "boy", visual: "🐋" },
      { type: "teach", title: "X is for X-ray", content: "X often sounds like KS at the end of words!", character: "boy", visual: "🩻" },
      { type: "quiz", title: "Quiz!", content: "Whale starts with...", options: ["V", "X", "W", "Y"], correct: 2 },
    ],
  },
  {
    id: "alpha-yz-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Letters Y & Z",
    description: "The last two letters!",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Y and Z!", content: "The last two letters of the alphabet!", character: "boy", visual: "YZ" },
      { type: "teach", title: "Y is for Yo-yo", content: "Y can sound like YUH or IH!", character: "boy", visual: "🪀" },
      { type: "teach", title: "Z is for Zebra", content: "Z makes ZZZ like a bee!", character: "boy", visual: "🦓" },
      { type: "funfact", title: "Fun Fact!", content: "In America they say Zee. In the UK we often say Zed!", visual: "🇬🇧", funFact: "The alphabet song tune is the same as Twinkle Twinkle Little Star!" },
      { type: "quiz", title: "Final quiz!", content: "Zebra starts with...", options: ["Y", "X", "Z", "A"], correct: 2 },
    ],
  },
  {
    id: "alpha-upper-lower-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Big & Small Letters",
    description: "Uppercase and lowercase",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Aa Bb Cc!", content: "Every letter has a BIG and small version!", character: "boy", visual: "Aa" },
      { type: "teach", title: "Capital letters", content: "Capitals start sentences and names!", character: "boy", visual: "A" },
      { type: "teach", title: "Lowercase", content: "Most writing uses small letters — they're faster!", character: "boy", visual: "a" },
      { type: "match", title: "Match big & small!", content: "Match each capital to its lowercase!", pairs: [["A", "a"], ["B", "b"], ["C", "c"], ["D", "d"]] },
      { type: "quiz", title: "Quiz!", content: "Which is a capital letter?", options: ["g", "H", "k", "m"], correct: 1 },
    ],
  },
  {
    id: "alpha-digraphs-1",
    subjectId: "alphabet",
    ageGroup: "6-8",
    title: "Digraphs SH & CH",
    description: "Two letters, one sound",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Digraphs!", content: "Sometimes two letters make ONE sound together!", character: "boy", visual: "SH CH" },
      { type: "teach", title: "SH", content: "SH like in ship, shell, fish!", character: "boy", visual: "🚢" },
      { type: "teach", title: "CH", content: "CH like in chat, cheese, lunch!", character: "boy", visual: "🧀" },
      { type: "interact", title: "Which digraph?", content: "Fi__ starts with SH", options: ["ch", "sh", "th", "ck"], correct: 1 },
      { type: "quiz", title: "Digraph quiz!", content: "Cheese starts with...", options: ["SH", "CH", "TH", "CK"], correct: 1 },
    ],
  },
  {
    id: "alpha-silent-e-1",
    subjectId: "alphabet",
    ageGroup: "6-8",
    title: "Magic E",
    description: "Silent e changes vowel sounds",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Magic E!", content: "A silent e at the end can change how the vowel sounds!", character: "boy", visual: "✨" },
      { type: "teach", title: "Cap → Cape", content: "Cap has a short A. Cape has a long A!", character: "boy", visual: "🧢" },
      { type: "teach", title: "Kit → Kite", content: "The magic e makes the I say its name!", character: "boy", visual: "🪁" },
      { type: "funfact", title: "Fun Fact!", content: "Silent letters exist in knight, island, and psychology!", visual: "🤫", funFact: "About 60% of English words have silent letters somewhere!" },
      { type: "quiz", title: "Magic E quiz!", content: "Which word has a magic e?", options: ["Cat", "Cake", "Cup", "Can"], correct: 1 },
    ],
  },
  {
    id: "alpha-alphabet-song-1",
    subjectId: "alphabet",
    ageGroup: "2-4",
    title: "The Alphabet Song",
    description: "Sing A to Z",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Sing the alphabet!", content: "Let's sing all 26 letters together!", character: "boy", visual: "🎵" },
      { type: "teach", title: "A to M", content: "A B C D E F G H I J K L M — sing along!", character: "boy", visual: "🔤", voiceText: "A B C D E F G H I J K L M!" },
      { type: "teach", title: "N to Z", content: "N O P Q R S T U V W X Y Z!", character: "boy", visual: "🔤", voiceText: "N O P Q R S T U V W X Y and Z!" },
      { type: "story", title: "Concert time", content: "Boy sang the whole alphabet at a school concert. Everyone clapped!", character: "boy", visual: "👏" },
      { type: "quiz", title: "Order quiz!", content: "Which letter comes after P?", options: ["O", "Q", "R", "S"], correct: 1 },
    ],
  },
  {
    id: "alpha-rhyme-letters-1",
    subjectId: "alphabet",
    ageGroup: "4-6",
    title: "Letter Rhymes",
    description: "Remember letters with rhymes",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Letter rhymes!", content: "Little rhymes help remember tricky letters!", character: "boy", visual: "🎶" },
      { type: "teach", title: "Q needs U", content: "Q is lonely without U — queen, quick, quilt!", character: "boy", visual: "QU" },
      { type: "teach", title: "X marks the spot", content: "X sounds like KS in fox and box!", character: "boy", visual: "🗺️" },
      { type: "interact", title: "Q and...", content: "Q almost always needs...", options: ["A", "E", "U", "I"], correct: 2 },
      { type: "quiz", title: "Quiz!", content: "Fox ends with the sound...", options: ["SH", "CH", "KS", "NG"], correct: 2 },
    ],
  },
];
