import type { Lesson } from "../lessons-data";

export const SCIENCE_GEO_SUPPLEMENT: Lesson[] = [
  // ── SCIENCE ──
  {
    id: "science-matter-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Solids, Liquids & Gases",
    description: "States of matter",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Matter!", content: "Everything is solid, liquid or gas!", character: "owl", visual: "🧊💧💨" },
      { type: "teach", title: "Solids", content: "Ice and rocks keep their shape!", character: "owl", visual: "🧊" },
      { type: "teach", title: "Liquids", content: "Water flows and takes the shape of its container!", character: "owl", visual: "💧" },
      { type: "funfact", title: "Fun Fact!", content: "Glass is actually a very slow-moving liquid — it flows over hundreds of years!", visual: "🪟", funFact: "Water is the only substance that expands when it freezes — that's why ice floats!" },
      { type: "quiz", title: "Matter quiz!", content: "Steam is a...", options: ["Solid", "Liquid", "Gas", "Rock"], correct: 2 },
    ],
  },
  {
    id: "science-forces-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Pushes & Pulls",
    description: "Forces move things",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Forces!", content: "A force is a push or a pull that moves things!", character: "owl", visual: "💪" },
      { type: "teach", title: "Push", content: "Push a swing to make it move!", character: "owl", visual: "🛝" },
      { type: "teach", title: "Pull", content: "Pull open a door to go through!", character: "owl", visual: "🚪" },
      { type: "experiment", title: "Force test!", content: "Push and pull different objects. Which needs more force?", experiment: { title: "Push Pull Test", materials: ["Toys", "Chair", "Ball"], steps: ["Try pushing each object", "Try pulling each object", "Which was hardest to move?", "Heavy things need more force!"] } },
      { type: "quiz", title: "Force quiz!", content: "Gravity pulls you...", options: ["Up", "Sideways", "Down", "Around"], correct: 2 },
    ],
  },
  {
    id: "science-light-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Light & Shadows",
    description: "How light works",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Light!", content: "Light lets us see. Block it and you get a shadow!", character: "owl", visual: "💡" },
      { type: "teach", title: "Sources of light", content: "The Sun, lamps and fire all give off light!", character: "owl", visual: "☀️" },
      { type: "teach", title: "Shadows", content: "Stand in front of a torch — your shadow appears behind you!", character: "owl", visual: "👤" },
      { type: "experiment", title: "Shadow puppets!", content: "Make shadow animals on the wall with a torch!", experiment: { title: "Shadow Theatre", materials: ["Torch or lamp", "Wall", "Your hands"], steps: ["Shine light at a wall", "Put hands in front of light", "Make animal shapes", "Can a grown-up guess your animal?"] } },
      { type: "quiz", title: "Light quiz!", content: "Shadows form when light is...", options: ["Blocked", "Bright", "Colourful", "Loud"], correct: 0 },
    ],
  },
  {
    id: "science-sound-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Sound Waves",
    description: "How we hear",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Sound!", content: "Sound travels in invisible waves to your ears!", character: "owl", visual: "🔊" },
      { type: "teach", title: "Vibration", content: "Pluck a rubber band — it vibrates and makes sound!", character: "owl", visual: "🎸" },
      { type: "funfact", title: "Fun Fact!", content: "There is no sound in space — astronauts use radios!", visual: "🚀", funFact: "Sound travels faster in water than in air. Whales can hear each other from hundreds of miles away!" },
      { type: "interact", title: "Louder or quieter?", content: "Banging a drum hard makes...", options: ["Quieter sound", "Louder sound", "No sound", "Light"], correct: 1 },
      { type: "quiz", title: "Sound quiz!", content: "We hear with our...", options: ["Eyes", "Ears", "Nose", "Hands"], correct: 1 },
    ],
  },
  {
    id: "science-seasons-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Seasons",
    description: "Spring, summer, autumn, winter",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Seasons!", content: "Earth tilts as it orbits the Sun — that makes seasons!", character: "owl", visual: "🍂☀️" },
      { type: "teach", title: "Spring", content: "Flowers bloom and baby animals are born!", character: "owl", visual: "🌸" },
      { type: "teach", title: "Winter", content: "Days are short and cold in the UK!", character: "owl", visual: "❄️" },
      { type: "match", title: "Match the season!", content: "Match the picture to the season!", pairs: [["☀️🏖️", "Summer"], ["🍂🍁", "Autumn"], ["❄️⛄", "Winter"], ["🌸🐣", "Spring"]] },
      { type: "quiz", title: "Season quiz!", content: "How many seasons in a year?", options: ["2", "3", "4", "5"], correct: 2 },
    ],
  },
  {
    id: "science-recycle-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Recycling",
    description: "Reduce, reuse, recycle",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Recycle!", content: "Recycling turns old things into new things!", character: "owl", visual: "♻️" },
      { type: "teach", title: "Three Rs", content: "Reduce, Reuse, Recycle!", character: "owl", visual: "🌍" },
      { type: "experiment", title: "Sort the rubbish!", content: "Sort items at home into recycling bins!", experiment: { title: "Recycling Sort", materials: ["Clean recyclables", "Bins"], steps: ["Find paper, plastic, glass", "Sort into correct bins", "Ask a grown-up to check", "You helped the planet!"] } },
      { type: "funfact", title: "Fun Fact!", content: "Recycling one aluminium can saves enough energy to run a TV for 3 hours!", visual: "🥫", funFact: "Glass can be recycled forever without losing quality!" },
      { type: "quiz", title: "Recycle quiz!", content: "Which can usually be recycled?", options: ["Banana peel", "Plastic bottle", "Broken toy", "Food scraps"], correct: 1 },
    ],
  },
  {
    id: "science-dinosaurs-1",
    subjectId: "science",
    ageGroup: "4-6",
    title: "Dinosaurs",
    description: "Prehistoric giants",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Dinosaurs!", content: "Dinosaurs lived millions of years ago — before humans!", character: "owl", visual: "🦕" },
      { type: "teach", title: "T-Rex", content: "Tyrannosaurus Rex was a fierce meat-eater with tiny arms!", character: "owl", visual: "🦖" },
      { type: "teach", title: "Plant eaters", content: "Brachiosaurus ate plants and had very long necks!", character: "owl", visual: "🌿" },
      { type: "funfact", title: "Fun Fact!", content: "Birds are actually living dinosaurs — they evolved from small feathered dinosaurs!", visual: "🐦", funFact: "The biggest dinosaur was Argentinosaurus — as long as three buses!" },
      { type: "quiz", title: "Dino quiz!", content: "T-Rex ate...", options: ["Plants only", "Meat", "Rocks", "Clouds"], correct: 1 },
    ],
  },
  {
    id: "science-magnets-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Magnets",
    description: "Attract and repel",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Magnets!", content: "Magnets pull metal objects towards them!", character: "owl", visual: "🧲" },
      { type: "teach", title: "North and south", content: "Opposite poles attract. Same poles push apart!", character: "owl", visual: "↔️" },
      { type: "experiment", title: "Magnet hunt!", content: "What sticks to a fridge magnet at home?", experiment: { title: "Magnet Test", materials: ["Fridge magnet", "Small metal and non-metal items"], steps: ["Try paper clips, coins, plastic", "What sticks?", "Only some metals are magnetic!", "Never swallow magnets!"] } },
      { type: "funfact", title: "Fun Fact!", content: "Earth itself is a giant magnet — that is why compass needles point north!", visual: "🧭", funFact: "Some trains float above tracks using powerful magnets called maglev!" },
      { type: "quiz", title: "Magnet quiz!", content: "Magnets attract...", options: ["All plastics", "Some metals", "Wood", "Water"], correct: 1 },
    ],
  },
  {
    id: "science-food-chains-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Food Chains",
    description: "Who eats whom",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Food chains!", content: "Energy passes from plants to animals in a chain!", character: "owl", visual: "🌿🐰🦊" },
      { type: "teach", title: "Producers", content: "Plants make food from sunlight — they start the chain!", character: "owl", visual: "🌱" },
      { type: "teach", title: "Predators", content: "A fox eats a rabbit. The rabbit ate grass!", character: "owl", visual: "🦊" },
      { type: "story", title: "Owl's dinner", content: "Owl eats a mouse that ate seeds. That's a food chain!", character: "owl", visual: "🌾" },
      { type: "quiz", title: "Chain quiz!", content: "What starts most food chains?", options: ["Rocks", "Plants", "Cars", "Clouds"], correct: 1 },
    ],
  },
  {
    id: "science-electricity-1",
    subjectId: "science",
    ageGroup: "6-8",
    title: "Electricity Safety",
    description: "Stay safe with electricity",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Electricity!", content: "Electricity powers our homes but must be treated with respect!", character: "owl", visual: "⚡" },
      { type: "teach", title: "Never touch plugs with wet hands", content: "Water and electricity are a dangerous mix!", character: "owl", visual: "💧⚡" },
      { type: "teach", title: "Ask a grown-up", content: "Only grown-ups change plugs and batteries!", character: "owl", visual: "👨‍👩‍👧" },
      { type: "funfact", title: "Fun Fact!", content: "Lightning is a giant natural spark of electricity!", visual: "🌩️", funFact: "A bolt of lightning is hotter than the surface of the Sun!" },
      { type: "quiz", title: "Safety quiz!", content: "Wet hands near plugs are...", options: ["Safe", "Fun", "Dangerous", "Helpful"], correct: 2 },
    ],
  },
  // ── GEOGRAPHY ──
  {
    id: "geo-maps-1",
    subjectId: "geography",
    ageGroup: "4-6",
    title: "Reading Maps",
    description: "Symbols and keys",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Maps!", content: "Maps show us where places are from above!", character: "elephant", visual: "🗺️" },
      { type: "teach", title: "Map key", content: "Symbols on a map tell you what things are — trees, roads, rivers!", character: "elephant", visual: "🔑" },
      { type: "teach", title: "North", content: "Most maps point north at the top!", character: "elephant", visual: "🧭" },
      { type: "experiment", title: "Draw a map!", content: "Draw a map of your bedroom from above!", experiment: { title: "Bedroom Map", materials: ["Paper", "Pencil", "Ruler"], steps: ["Draw your room shape", "Add bed, door, window", "Make a key for symbols", "Show a grown-up your map!"] } },
      { type: "quiz", title: "Map quiz!", content: "A map shows places from...", options: ["Underground", "Above", "Inside", "Behind"], correct: 1 },
    ],
  },
  {
    id: "geo-mountains-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "Mountains & Valleys",
    description: "High and low land",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Mountains!", content: "Mountains are the highest land on Earth!", character: "elephant", visual: "⛰️" },
      { type: "teach", title: "Everest", content: "Mount Everest is the tallest mountain on Earth!", character: "elephant", visual: "🏔️" },
      { type: "funfact", title: "Fun Fact!", content: "Mountains form when tectonic plates crash together!", visual: "🌍", funFact: "The Himalayas grow about 1 cm taller every year!" },
      { type: "interact", title: "Highest?", content: "Which is highest?", options: ["Hill", "Mountain", "Valley", "Beach"], correct: 1 },
      { type: "quiz", title: "Mountain quiz!", content: "Valleys are...", options: ["High", "Low land between hills", "In the ocean", "In space"], correct: 1 },
    ],
  },
  {
    id: "geo-rivers-1",
    subjectId: "geography",
    ageGroup: "4-6",
    title: "Rivers",
    description: "Flowing water to the sea",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Rivers!", content: "Rivers flow from hills to the sea!", character: "elephant", visual: "🏞️" },
      { type: "teach", title: "Source to mouth", content: "The start is the source. The end is the mouth at the sea!", character: "elephant", visual: "🌊" },
      { type: "teach", title: "The Nile", content: "The Nile in Africa is one of the longest rivers in the world!", character: "elephant", visual: "🐊" },
      { type: "funfact", title: "Fun Fact!", content: "The Amazon River carries more water than any other river on Earth!", visual: "🌊", funFact: "Rivers carve deep valleys over millions of years — the Grand Canyon was shaped by the Colorado River!" },
      { type: "interact", title: "River parts!", content: "Where a river starts is called the...", options: ["Mouth", "Source", "Cloud", "Mountain top only"], correct: 1 },
      { type: "quiz", title: "River quiz!", content: "Rivers usually flow...", options: ["Uphill", "To the sea", "To space", "Nowhere"], correct: 1 },
    ],
  },
  {
    id: "geo-volcanoes-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "Volcanoes",
    description: "Fire mountains",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Volcanoes!", content: "Volcanoes are openings in Earth that can erupt hot lava!", character: "elephant", visual: "🌋" },
      { type: "teach", title: "Magma", content: "Hot melted rock underground is called magma. Above ground it's lava!", character: "elephant", visual: "🔥" },
      { type: "funfact", title: "Fun Fact!", content: "Most volcanoes are under the ocean!", visual: "🌊", funFact: "There are about 1,500 active volcanoes on Earth!" },
      { type: "interact", title: "Hot or cold?", content: "Magma underground becomes ___ above ground.", options: ["Ice", "Lava", "Wind", "Sand"], correct: 1 },
      { type: "quiz", title: "Volcano quiz!", content: "Lava is...", options: ["Cold ice", "Hot melted rock", "Water", "Wind"], correct: 1 },
    ],
  },
  {
    id: "geo-capital-cities-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "Capital Cities",
    description: "Cities that lead countries",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Capitals!", content: "Every country has a capital city — often where the government works!", character: "elephant", visual: "🏛️" },
      { type: "teach", title: "Paris", content: "Paris is the capital of France — home of the Eiffel Tower!", character: "elephant", visual: "🗼" },
      { type: "teach", title: "Tokyo", content: "Tokyo is the capital of Japan — one of the biggest cities on Earth!", character: "elephant", visual: "🗾" },
      { type: "match", title: "Match capitals!", content: "Match country to capital!", pairs: [["UK", "London"], ["France", "Paris"], ["Japan", "Tokyo"], ["USA", "Washington"]] },
      { type: "quiz", title: "Capital quiz!", content: "London is the capital of...", options: ["France", "UK", "USA", "Japan"], correct: 1 },
    ],
  },
  {
    id: "geo-islands-1",
    subjectId: "geography",
    ageGroup: "4-6",
    title: "Islands",
    description: "Land surrounded by water",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Islands!", content: "An island is land with water all around it!", character: "elephant", visual: "🏝️" },
      { type: "teach", title: "UK is an island", content: "Great Britain is an island nation!", character: "elephant", visual: "🇬🇧" },
      { type: "interact", title: "Island spot!", content: "Which is surrounded by water on all sides?", options: ["A hill", "An island", "A road", "A cloud"], correct: 1 },
      { type: "funfact", title: "Fun Fact!", content: "Greenland is the world's biggest island!", visual: "🧊", funFact: "Australia is so big some call it a continent, not just an island!" },
      { type: "quiz", title: "Island quiz!", content: "An island is surrounded by...", options: ["Sand", "Water", "Mountains", "Ice only"], correct: 1 },
    ],
  },
  {
    id: "geo-population-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "People on Earth",
    description: "Population around the world",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Population!", content: "Over 8 billion people live on Earth!", character: "elephant", visual: "👥" },
      { type: "teach", title: "Crowded cities", content: "Tokyo and Delhi have tens of millions of people!", character: "elephant", visual: "🏙️" },
      { type: "funfact", title: "Fun Fact!", content: "China and India each have over 1 billion people!", visual: "🇨🇳", funFact: "The global population grows by about 200,000 people every day!" },
      { type: "interact", title: "Big cities!", content: "Tokyo and Delhi are famous for being very...", options: ["Empty", "Crowded", "Cold only", "Underwater"], correct: 1 },
      { type: "quiz", title: "Population quiz!", content: "Population means...", options: ["Number of people", "Number of trees", "Weather", "Rocks"], correct: 0 },
    ],
  },
  {
    id: "geo-compass-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "Compass Directions",
    description: "North, south, east, west",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Directions!", content: "N S E W — never eat shredded wheat helps you remember!", character: "elephant", visual: "🧭" },
      { type: "teach", title: "North", content: "A compass needle points north!", character: "elephant", visual: "⬆️" },
      { type: "teach", title: "Opposite pairs", content: "North-South and East-West are opposites!", character: "elephant", visual: "↔️" },
      { type: "interact", title: "Opposite!", content: "Opposite of North is...", options: ["East", "South", "West", "Up"], correct: 1 },
      { type: "quiz", title: "Compass quiz!", content: "How many main compass directions?", options: ["2", "4", "6", "8"], correct: 1 },
    ],
  },
  {
    id: "geo-farming-1",
    subjectId: "geography",
    ageGroup: "4-6",
    title: "Farms & Food",
    description: "Where our food grows",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Farms!", content: "Farmers grow food that ends up on your plate!", character: "elephant", visual: "🚜" },
      { type: "teach", title: "Crops", content: "Wheat becomes bread. Cows give milk!", character: "elephant", visual: "🌾🐄" },
      { type: "story", title: "From field to shop", content: "Elephant visited a farm then saw the same apples in a shop!", character: "elephant", visual: "🍎" },
      { type: "funfact", title: "Fun Fact!", content: "Honey never spoils — archaeologists found edible honey in ancient Egyptian tombs!", visual: "🍯", funFact: "Farmers help feed billions of people — agriculture was invented over 10,000 years ago!" },
      { type: "quiz", title: "Farm quiz!", content: "Bread often comes from...", options: ["Rocks", "Wheat", "Plastic", "Metal"], correct: 1 },
    ],
  },
  {
    id: "geo-earth-layers-1",
    subjectId: "geography",
    ageGroup: "6-8",
    title: "Inside the Earth",
    description: "Layers under our feet",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Inside Earth!", content: "Earth has layers like an onion — crust, mantle, core!", character: "elephant", visual: "🌍" },
      { type: "teach", title: "Crust", content: "We live on the crust — the thin rocky shell!", character: "elephant", visual: "🪨" },
      { type: "teach", title: "Core", content: "The core is super hot — as hot as the surface of the Sun!", character: "elephant", visual: "🔥" },
      { type: "funfact", title: "Fun Fact!", content: "We have never drilled all the way through the crust!", visual: "⛏️", funFact: "The deepest hole humans dug is about 12 km — still not through the crust!" },
      { type: "quiz", title: "Earth quiz!", content: "We live on the...", options: ["Core", "Crust", "Mantle only", "Moon"], correct: 1 },
    ],
  },
];
