import type { Lesson } from "../lessons-data";

export const CODING_SOCIAL_ARTS_MOTOR_SUPPLEMENT: Lesson[] = [
  // ── CODING ──
  {
    id: "coding-variables-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Variables",
    description: "Boxes that store information",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Variables!", content: "A variable is like a labelled box that stores a value!", character: "penguin", visual: "📦" },
      { type: "teach", title: "Score = 0", content: "In games, score is a variable that changes when you win points!", character: "penguin", visual: "🎮" },
      { type: "funfact", title: "Fun Fact!", content: "The word variable comes from the Latin word for change!", visual: "🔄", funFact: "The first programming language FORTRAN was created in 1957!" },
      { type: "interact", title: "What changes?", content: "In a game, which is usually a variable?", options: ["The sky colour", "Your score", "The word Hello", "Gravity on Earth"], correct: 1 },
      { type: "quiz", title: "Variable quiz!", content: "A variable stores...", options: ["Only pictures", "A value that can change", "Nothing", "Only sounds"], correct: 1 },
    ],
  },
  {
    id: "coding-debugging-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Debugging",
    description: "Finding and fixing bugs",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Debugging!", content: "A bug is a mistake in code. Debugging means finding and fixing it!", character: "penguin", visual: "🐛" },
      { type: "teach", title: "Check step by step", content: "Read your instructions one line at a time!", character: "penguin", visual: "🔍" },
      { type: "story", title: "Penguin's broken game", content: "Penguin's game would not start — he forgot to add fuel in step 1!", character: "penguin", visual: "🚀" },
      { type: "quiz", title: "Debug quiz!", content: "A bug in code is a...", options: ["Insect only", "Mistake", "Feature", "Colour"], correct: 1 },
    ],
  },
  {
    id: "coding-algorithms-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Algorithms",
    description: "A plan to solve a problem",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Algorithms!", content: "An algorithm is a clear plan to solve a problem step by step!", character: "penguin", visual: "📋" },
      { type: "teach", title: "Recipe = algorithm", content: "A cake recipe is an algorithm for baking!", character: "penguin", visual: "🎂" },
      { type: "experiment", title: "Robot algorithm!", content: "Write directions for a grown-up to cross a room without hitting furniture!", experiment: { title: "Human Robot", materials: ["Paper", "Furniture"], steps: ["Write step-by-step directions", "Grown-up is the robot", "They follow exactly — no guessing!", "Fix steps if robot goes wrong"] } },
      { type: "quiz", title: "Algorithm quiz!", content: "An algorithm must be...", options: ["Random", "Clear steps", "Secret", "One word"], correct: 1 },
    ],
  },
  {
    id: "coding-binary-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Binary Numbers",
    description: "Computer language of 0s and 1s",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Binary!", content: "Computers use only 0 and 1 — that's binary!", character: "penguin", visual: "01" },
      { type: "teach", title: "On and off", content: "1 means on, 0 means off — like a light switch!", character: "penguin", visual: "💡" },
      { type: "funfact", title: "Fun Fact!", content: "Every photo, song and game on a phone is stored as billions of 0s and 1s!", visual: "📱", funFact: "The word bit comes from binary digit — one 0 or 1!" },
      { type: "quiz", title: "Binary quiz!", content: "Binary uses which digits?", options: ["0-9", "0 and 1", "A-Z", "1-5"], correct: 1 },
    ],
  },
  {
    id: "coding-events-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Events",
    description: "When something happens, code reacts",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Events!", content: "When you tap a button, the game reacts — that's an event!", character: "penguin", visual: "👆" },
      { type: "teach", title: "On click", content: "When player clicks jump THEN character jumps!", character: "penguin", visual: "⬆️" },
      { type: "interact", title: "Event!", content: "Pressing a doorbell is an event. What happens?", options: ["Nothing", "Bell rings", "Tree grows", "Sun sets"], correct: 1 },
      { type: "quiz", title: "Event quiz!", content: "An event is...", options: ["Something that happens", "A type of food", "A colour", "A mountain"], correct: 0 },
    ],
  },
  {
    id: "coding-decomposition-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Breaking Problems Down",
    description: "Decomposition",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Break it down!", content: "Big problems are easier when you split them into small steps!", character: "penguin", visual: "🧩" },
      { type: "teach", title: "Build a castle", content: "First dig moat, then walls, then towers — not all at once!", character: "penguin", visual: "🏰" },
      { type: "quiz", title: "Decomposition quiz!", content: "Decomposition means...", options: ["Breaking into smaller parts", "Giving up", "One giant step", "Deleting code"], correct: 0 },
    ],
  },
  {
    id: "coding-coordinates-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Coordinates",
    description: "X and Y on a grid",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Coordinates!", content: "Games use X and Y to know where things are on screen!", character: "penguin", visual: "📍" },
      { type: "teach", title: "X goes across", content: "X is horizontal — left and right!", character: "penguin", visual: "↔️" },
      { type: "teach", title: "Y goes up", content: "Y is vertical — up and down!", character: "penguin", visual: "↕️" },
      { type: "interact", title: "Find the point!", content: "Point (0,0) is usually at the...", options: ["Top right", "Bottom corner", "Middle", "Sky"], correct: 1 },
      { type: "quiz", title: "Coordinate quiz!", content: "X measures...", options: ["Up-down", "Left-right", "Colour", "Sound"], correct: 1 },
    ],
  },
  {
    id: "coding-functions-1",
    subjectId: "coding",
    ageGroup: "6-8",
    title: "Functions",
    description: "Reusable code blocks",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Functions!", content: "A function is a named set of steps you can use again and again!", character: "penguin", visual: "📦" },
      { type: "teach", title: "Jump function", content: "Define jump once — call it every time the player presses a button!", character: "penguin", visual: "⬆️" },
      { type: "funfact", title: "Fun Fact!", content: "Functions save time and stop copy-paste mistakes!", visual: "⏱️", funFact: "Professional programmers reuse functions millions of times in big apps!" },
      { type: "quiz", title: "Function quiz!", content: "A function lets you...", options: ["Reuse steps", "Delete the computer", "Skip thinking", "Avoid order"], correct: 0 },
    ],
  },
  // ── SOCIAL SKILLS ──
  {
    id: "social-friendship-1",
    subjectId: "social-skills",
    ageGroup: "4-6",
    title: "Making Friends",
    description: "How to start friendships",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Friends!", content: "Friends are people who care about each other and have fun together!", character: "grandma", visual: "👫" },
      { type: "teach", title: "Say hello", content: "A smile and hello is a great way to start!", character: "grandma", visual: "👋" },
      { type: "teach", title: "Take turns", content: "Games are more fun when everyone gets a turn!", character: "grandma", visual: "🎲" },
      { type: "quiz", title: "Friend quiz!", content: "A good way to make friends is to...", options: ["Ignore people", "Smile and say hello", "Shout", "Take all toys"], correct: 1 },
    ],
  },
  {
    id: "social-empathy-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "Empathy",
    description: "Understanding how others feel",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Empathy!", content: "Empathy means imagining how someone else feels!", character: "grandma", visual: "💛" },
      { type: "teach", title: "Walk in their shoes", content: "If your friend fell over, how would you want to be treated?", character: "grandma", visual: "👟" },
      { type: "story", title: "New at school", content: "A new child felt shy. Grandma sat with them at lunch. They smiled!", character: "grandma", visual: "🏫" },
      { type: "quiz", title: "Empathy quiz!", content: "Empathy means...", options: ["Ignoring others", "Understanding feelings", "Winning always", "Being loud"], correct: 1 },
    ],
  },
  {
    id: "social-manners-1",
    subjectId: "social-skills",
    ageGroup: "4-6",
    title: "Please & Thank You",
    description: "Polite words matter",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Manners!", content: "Please and thank you show respect and kindness!", character: "grandma", visual: "🙏" },
      { type: "teach", title: "Please", content: "Say please when you ask for something!", character: "grandma", visual: "✨" },
      { type: "teach", title: "Thank you", content: "Say thank you when someone helps you!", character: "grandma", visual: "💝" },
      { type: "interact", title: "Polite words!", content: "You want a biscuit. You say...", options: ["Give me!", "Please may I have a biscuit?", "Nothing", "Go away"], correct: 1 },
      { type: "quiz", title: "Manners quiz!", content: "Thank you shows...", options: ["Anger", "Gratitude", "Sleepiness", "Hunger"], correct: 1 },
    ],
  },
  {
    id: "social-teamwork-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "Teamwork",
    description: "Working together",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Teamwork!", content: "Teams achieve more when everyone helps!", character: "grandma", visual: "🤝" },
      { type: "teach", title: "Everyone has a role", content: "In a team project, each person can do something special!", character: "grandma", visual: "⭐" },
      { type: "experiment", title: "Team challenge!", content: "Build a tower of cups with a friend — no hands alone!", experiment: { title: "Cup Tower Team", materials: ["Plastic cups", "A friend"], steps: ["Take turns placing cups", "Support each other", "Celebrate when done", "What was easier together?"] } },
      { type: "quiz", title: "Team quiz!", content: "Teamwork means...", options: ["One person does all", "Working together", "Giving up", "Cheating"], correct: 1 },
    ],
  },
  {
    id: "social-confidence-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "Trying New Things",
    description: "Building confidence",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Be brave!", content: "Trying new things can feel scary but helps you grow!", character: "grandma", visual: "🌟" },
      { type: "teach", title: "It's okay to fail", content: "Every expert was once a beginner who made mistakes!", character: "grandma", visual: "📈" },
      { type: "funfact", title: "Fun Fact!", content: "Your brain grows new connections when you practise hard things!", visual: "🧠", funFact: "Scientists call this neuroplasticity — your brain is like a muscle!" },
      { type: "quiz", title: "Confidence quiz!", content: "If you fail first time you should...", options: ["Give up forever", "Try again and practise", "Cry only", "Blame others"], correct: 1 },
    ],
  },
  {
    id: "social-listening-1",
    subjectId: "social-skills",
    ageGroup: "4-6",
    title: "Good Listening",
    description: "Ears open, mouth quiet",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Listen!", content: "Good listeners learn more and make better friends!", character: "grandma", visual: "👂" },
      { type: "teach", title: "Look at the speaker", content: "Eyes on the person helps your brain focus!", character: "grandma", visual: "👀" },
      { type: "quiz", title: "Listening quiz!", content: "A good listener...", options: ["Interrupts", "Looks and pays attention", "Walks away", "Sings loudly"], correct: 1 },
    ],
  },
  {
    id: "social-apologize-1",
    subjectId: "social-skills",
    ageGroup: "4-6",
    title: "Saying Sorry",
    description: "Fixing mistakes with words",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Sorry!", content: "Everyone makes mistakes. Sorry helps fix hurt feelings!", character: "grandma", visual: "💚" },
      { type: "teach", title: "Mean it", content: "A real sorry includes what you did and how to make it better!", character: "grandma", visual: "🤗" },
      { type: "story", title: "Spilled paint", content: "Grandma knocked paint over. She said sorry and helped clean up!", character: "grandma", visual: "🎨" },
      { type: "quiz", title: "Sorry quiz!", content: "Sorry is for when you...", options: ["Win a game", "Hurt someone by mistake", "Eat lunch", "Sleep"], correct: 1 },
    ],
  },
  {
    id: "social-boundaries-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "Personal Space",
    description: "Respecting boundaries",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Personal space!", content: "Everyone needs space around their body to feel safe!", character: "grandma", visual: "🫧" },
      { type: "teach", title: "Ask first", content: "Ask before hugs if someone looks unsure!", character: "grandma", visual: "🤗" },
      { type: "quiz", title: "Space quiz!", content: "If someone says stop tickling you should...", options: ["Keep going", "Stop immediately", "Run away angry", "Laugh only"], correct: 1 },
    ],
  },
  {
    id: "social-celebrate-1",
    subjectId: "social-skills",
    ageGroup: "4-6",
    title: "Celebrating Others",
    description: "Cheering for friends",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Cheer others!", content: "When friends do well, celebrate with them — not just yourself!", character: "grandma", visual: "🎉" },
      { type: "teach", title: "Clap for friends", content: "You can be happy for someone else's win!", character: "grandma", visual: "👏" },
      { type: "quiz", title: "Celebrate quiz!", content: "Your friend wins a race. You...", options: ["Get angry", "Clap and say well done", "Leave", "Cry"], correct: 1 },
    ],
  },
  {
    id: "social-worry-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "When We Worry",
    description: "Coping with worry",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Worry!", content: "Everyone worries sometimes. There are ways to feel calmer!", character: "grandma", visual: "🌈" },
      { type: "teach", title: "Talk to someone", content: "Telling a trusted grown-up helps worries shrink!", character: "grandma", visual: "💬" },
      { type: "teach", title: "Belly breathing", content: "Breathe in slowly for 4, out for 4. Repeat five times!", character: "grandma", visual: "🌬️" },
      { type: "experiment", title: "Calm jar!", content: "Shake a jar of glitter in water and watch it settle — like your mind!", experiment: { title: "Calm Glitter Jar", materials: ["Jar with lid", "Water", "Glitter", "Glue optional"], steps: ["Fill jar with water and glitter", "Shake it up", "Watch glitter settle", "Breathe as it settles"] } },
      { type: "quiz", title: "Worry quiz!", content: "When worried, a good first step is...", options: ["Keep it secret always", "Talk to someone you trust", "Shout", "Hide forever"], correct: 1 },
    ],
  },
  {
    id: "social-inclusion-1",
    subjectId: "social-skills",
    ageGroup: "6-8",
    title: "Including Everyone",
    description: "Nobody left out",
    coinsReward: 20,
    xpReward: 25,
    slides: [
      { type: "intro", title: "Include everyone!", content: "Games are better when no one is left out!", character: "grandma", visual: "🌍" },
      { type: "teach", title: "Invite others", content: "See someone alone? Ask them to join!", character: "grandma", visual: "🤝" },
      { type: "funfact", title: "Fun Fact!", content: "Schools with inclusive playgrounds have happier students!", visual: "🏫", funFact: "Including others builds empathy skills that last your whole life!" },
      { type: "quiz", title: "Include quiz!", content: "Someone is alone at playtime. You...", options: ["Ignore them", "Invite them to play", "Laugh", "Walk past"], correct: 1 },
    ],
  },
  // ── ARTS ──
  {
    id: "arts-secondary-colours-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Secondary Colours",
    description: "Orange, green and purple",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Secondary colours!", content: "Mix two primary colours to get secondary colours!", character: "unicorn", visual: "🟠🟢🟣" },
      { type: "teach", title: "Orange", content: "Red + yellow = orange!", character: "unicorn", visual: "🟠" },
      { type: "teach", title: "Green & purple", content: "Blue + yellow = green. Red + blue = purple!", character: "unicorn", visual: "🟢🟣" },
      { type: "quiz", title: "Colour quiz!", content: "Blue + yellow = ?", options: ["Orange", "Green", "Purple", "Pink"], correct: 1 },
    ],
  },
  {
    id: "arts-drawing-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Drawing Shapes",
    description: "Build pictures from shapes",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Draw with shapes!", content: "Circles and rectangles can become animals and houses!", character: "unicorn", visual: "✏️" },
      { type: "teach", title: "House", content: "Square + triangle roof = house!", character: "unicorn", visual: "🏠" },
      { type: "experiment", title: "Shape art!", content: "Draw an animal using only circles and triangles!", experiment: { title: "Shape Animal", materials: ["Paper", "Pencil", "Crayons"], steps: ["Draw circles for body and head", "Add triangles for ears", "Colour in", "Name your creature!"] } },
      { type: "quiz", title: "Draw quiz!", content: "A roof is often shaped like a...", options: ["Circle", "Triangle", "Dot", "Line"], correct: 1 },
    ],
  },
  {
    id: "arts-music-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Music & Rhythm",
    description: "Beat and tempo",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Music!", content: "Music has a beat you can clap along to!", character: "unicorn", visual: "🎵" },
      { type: "teach", title: "Fast and slow", content: "Tempo means how fast the music goes!", character: "unicorn", visual: "⏩⏪" },
      { type: "experiment", title: "Body percussion!", content: "Clap, stamp and pat your knees to make rhythms!", experiment: { title: "Rhythm Band", materials: ["Your body", "Optional pots as drums"], steps: ["Clap four beats", "Stamp feet twice", "Pat knees", "Put patterns together!"] } },
      { type: "quiz", title: "Music quiz!", content: "The beat is...", options: ["The steady pulse", "Only singing", "Silence", "A colour"], correct: 0 },
    ],
  },
  {
    id: "arts-sculpture-1",
    subjectId: "arts",
    ageGroup: "6-8",
    title: "Sculpture",
    description: "3D art you can touch",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Sculpture!", content: "Sculpture is art you can walk around and touch!", character: "unicorn", visual: "🗿" },
      { type: "teach", title: "Clay and stone", content: "Artists carve stone or shape clay into statues!", character: "unicorn", visual: "🪨" },
      { type: "funfact", title: "Fun Fact!", content: "The Great Sphinx in Egypt is over 4,500 years old!", visual: "🐫", funFact: "Michelangelo's David was carved from a single block of marble!" },
      { type: "quiz", title: "Sculpture quiz!", content: "Sculpture is usually...", options: ["Flat only", "3D", "Invisible", "Only sound"], correct: 1 },
    ],
  },
  {
    id: "arts-printmaking-1",
    subjectId: "arts",
    ageGroup: "6-8",
    title: "Printmaking",
    description: "Stamp and repeat",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Prints!", content: "Printmaking copies a design again and again!", character: "unicorn", visual: "🖨️" },
      { type: "teach", title: "Potato prints", content: "Cut a potato, dip in paint, stamp on paper!", character: "unicorn", visual: "🥔" },
      { type: "experiment", title: "Make prints!", content: "Try potato or sponge printing!", experiment: { title: "Potato Print", materials: ["Potato half", "Paint", "Paper", "Adult to cut potato"], steps: ["Adult cuts shape in potato", "Dip flat side in paint", "Press on paper", "Repeat to make a pattern"] } },
      { type: "quiz", title: "Print quiz!", content: "Printmaking creates...", options: ["One copy only", "Repeated images", "Only music", "Food"], correct: 1 },
    ],
  },
  {
    id: "arts-collage-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Collage",
    description: "Cut and stick art",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Collage!", content: "Glue paper, fabric and photos together to make new art!", character: "unicorn", visual: "✂️" },
      { type: "teach", title: "Layers", content: "Build pictures in layers — background first!", character: "unicorn", visual: "📄" },
      { type: "quiz", title: "Collage quiz!", content: "Collage uses...", options: ["Only water", "Cut and glued pieces", "Only pencils", "Nothing"], correct: 1 },
    ],
  },
  {
    id: "arts-warm-cool-1",
    subjectId: "arts",
    ageGroup: "6-8",
    title: "Warm & Cool Colours",
    description: "Mood in art",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Warm & cool!", content: "Reds and oranges feel warm. Blues feel cool!", character: "unicorn", visual: "🔥❄️" },
      { type: "teach", title: "Warm colours", content: "Sunset paintings often use warm reds and oranges!", character: "unicorn", visual: "🌅" },
      { type: "teach", title: "Cool colours", content: "Ocean scenes use cool blues and greens!", character: "unicorn", visual: "🌊" },
      { type: "interact", title: "Warm or cool?", content: "Fire colours are mostly...", options: ["Cool blue", "Warm red-orange", "Only green", "Black"], correct: 1 },
      { type: "quiz", title: "Colour mood quiz!", content: "Cool colours often feel...", options: ["Hot", "Calm and cold", "Loud", "Spicy"], correct: 1 },
    ],
  },
  {
    id: "arts-patterns-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Art Patterns",
    description: "Repeat shapes and colours",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Patterns!", content: "Stripes, spots and zigzags — patterns repeat!", character: "unicorn", visual: "〰️" },
      { type: "teach", title: "Repeat", content: "Red blue red blue — that's a repeating pattern!", character: "unicorn", visual: "🔴🔵" },
      { type: "experiment", title: "Pattern strip!", content: "Draw a strip of repeating shapes!", experiment: { title: "Pattern Paper", materials: ["Paper", "Crayons"], steps: ["Pick two shapes", "Repeat them in a row", "Use two colours", "Continue across the page"] } },
      { type: "quiz", title: "Pattern quiz!", content: "A pattern...", options: ["Changes randomly", "Repeats", "Disappears", "Is silent"], correct: 1 },
    ],
  },
  {
    id: "arts-self-portrait-1",
    subjectId: "arts",
    ageGroup: "6-8",
    title: "Self Portraits",
    description: "Draw yourself",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Portrait!", content: "A portrait is a picture of a person — you can draw yourself!", character: "unicorn", visual: "🪞" },
      { type: "teach", title: "Face shapes", content: "Oval face, eyes in the middle, mouth below nose!", character: "unicorn", visual: "😊" },
      { type: "experiment", title: "Mirror portrait!", content: "Look in a mirror and draw what you see!", experiment: { title: "Self Portrait", materials: ["Mirror", "Paper", "Pencil"], steps: ["Look at your face", "Draw oval outline", "Add eyes, nose, mouth", "Add hair and your style!"] } },
      { type: "quiz", title: "Portrait quiz!", content: "A self-portrait is a picture of...", options: ["Yourself", "A tree", "A car", "The sky"], correct: 0 },
    ],
  },
  {
    id: "arts-craft-1",
    subjectId: "arts",
    ageGroup: "4-6",
    title: "Craft & Making",
    description: "Hands-on creating",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Craft!", content: "Craft means making things with your hands!", character: "unicorn", visual: "🧶" },
      { type: "teach", title: "Paper craft", content: "Fold, cut and stick paper into amazing shapes!", character: "unicorn", visual: "📄" },
      { type: "story", title: "Unicorn's paper crown", content: "Unicorn folded paper into a sparkly crown!", character: "unicorn", visual: "👑" },
      { type: "quiz", title: "Craft quiz!", content: "Craft uses...", options: ["Only computers", "Hands and materials", "Only voice", "Magic spells"], correct: 1 },
    ],
  },
  // ── MOTOR SKILLS ──
  {
    id: "motor-gross-1",
    subjectId: "motor-skills",
    ageGroup: "4-6",
    title: "Gross Motor Skills",
    description: "Big body movements",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Big moves!", content: "Running, jumping and throwing use gross motor skills!", character: "frog", visual: "🏃" },
      { type: "teach", title: "Strong muscles", content: "Your legs and arms have big muscles for big moves!", character: "frog", visual: "💪" },
      { type: "experiment", title: "Obstacle course!", content: "Make a mini obstacle course in the garden or living room!", experiment: { title: "Obstacle Course", materials: ["Cushions", "Chairs", "Tape"], steps: ["Jump over a cushion", "Crawl under a chair", "Balance on a line", "Time yourself!"] } },
      { type: "quiz", title: "Gross motor quiz!", content: "Which uses gross motor skills?", options: ["Writing", "Running", "Threading beads", "Drawing"], correct: 1 },
    ],
  },
  {
    id: "motor-hand-eye-1",
    subjectId: "motor-skills",
    ageGroup: "4-6",
    title: "Hand-Eye Coordination",
    description: "Catch and throw",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Catch!", content: "Your eyes tell your hands where the ball is going!", character: "frog", visual: "⚽" },
      { type: "teach", title: "Watch the ball", content: "Keep eyes on the ball — not on your hands!", character: "frog", visual: "👀" },
      { type: "experiment", title: "Balloon keep-up!", content: "Keep a balloon in the air without letting it touch the floor!", experiment: { title: "Balloon Tap", materials: ["Balloon"], steps: ["Tap balloon up gently", "Move under it", "Count how many taps", "Try with a friend!"] } },
      { type: "quiz", title: "Coordination quiz!", content: "Catching needs eyes and...", options: ["Ears only", "Hands working together", "Feet only", "Nose"], correct: 1 },
    ],
  },
  {
    id: "motor-stretching-1",
    subjectId: "motor-skills",
    ageGroup: "2-4",
    title: "Stretching",
    description: "Warm up your body",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Stretch!", content: "Stretching wakes up your muscles gently!", character: "frog", visual: "🧘" },
      { type: "teach", title: "Reach high", content: "Reach arms up high like a tall tree!", character: "frog", visual: "🌳" },
      { type: "teach", title: "Touch toes", content: "Bend slowly and try to touch your toes!", character: "frog", visual: "👣" },
      { type: "quiz", title: "Stretch quiz!", content: "Stretching helps muscles feel...", options: ["More ready to move", "Broken", "Sleepy only", "Hungry"], correct: 0 },
    ],
  },
  {
    id: "motor-jumping-1",
    subjectId: "motor-skills",
    ageGroup: "2-4",
    title: "Jumping & Landing",
    description: "Safe jumps",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Jump!", content: "Bend knees, push off, land softly!", character: "frog", visual: "⬆️" },
      { type: "teach", title: "Soft landing", content: "Land on bent knees like a frog!", character: "frog", visual: "🐸" },
      { type: "experiment", title: "Jump lines!", content: "Tape lines on the floor and jump between them!", experiment: { title: "Line Jumps", materials: ["Masking tape", "Floor space"], steps: ["Tape lines on floor", "Jump with two feet", "Land softly", "How far can you jump?"] } },
      { type: "quiz", title: "Jump quiz!", content: "Land with...", options: ["Straight locked knees", "Bent knees softly", "One hand", "Eyes closed"], correct: 1 },
    ],
  },
  {
    id: "motor-cutting-1",
    subjectId: "motor-skills",
    ageGroup: "4-6",
    title: "Using Scissors",
    description: "Safe cutting practice",
    coinsReward: 15,
    xpReward: 20,
    slides: [
      { type: "intro", title: "Scissors!", content: "Scissors need grown-up scissors and supervision!", character: "frog", visual: "✂️" },
      { type: "teach", title: "Thumb on top", content: "Thumb in small hole, fingers below. Cut away from your body!", character: "frog", visual: "✋" },
      { type: "experiment", title: "Paper strips!", content: "Cut strips then snip fringe — with a grown-up!", experiment: { title: "Safe Cutting", materials: ["Child-safe scissors", "Paper", "Grown-up"], steps: ["Grown-up checks grip", "Cut straight strips", "Snip fringe", "Glue strips as grass in a picture"] } },
      { type: "quiz", title: "Scissors quiz!", content: "Cut...", options: ["Towards your fingers", "Away from your body", "While running", "At hair"], correct: 1 },
    ],
  },
  {
    id: "motor-threading-1",
    subjectId: "motor-skills",
    ageGroup: "4-6",
    title: "Threading Beads",
    description: "Precision practice",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Threading!", content: "Threading beads trains your fingers and eyes!", character: "frog", visual: "📿" },
      { type: "teach", title: "Steady hands", content: "Hold the string still and push the bead on!", character: "frog", visual: "✋" },
      { type: "experiment", title: "Bead necklace!", content: "Thread pasta or beads onto string!", experiment: { title: "Bead Threading", materials: ["String", "Large beads or tube pasta"], steps: ["Tie knot at end", "Thread beads one by one", "Make a pattern", "Tie ends with grown-up help"] } },
      { type: "quiz", title: "Threading quiz!", content: "Threading improves...", options: ["Fine motor skills", "Only shouting", "Sleep", "Eating"], correct: 0 },
    ],
  },
  {
    id: "motor-yoga-1",
    subjectId: "motor-skills",
    ageGroup: "4-6",
    title: "Animal Yoga",
    description: "Pose like animals",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Animal yoga!", content: "Stretch your body like animals do!", character: "frog", visual: "🐱" },
      { type: "teach", title: "Cat pose", content: "Arch your back up like a scared cat!", character: "frog", visual: "🐈" },
      { type: "teach", title: "Downward dog", content: "Hands and feet on floor, bottom in the air!", character: "frog", visual: "🐕" },
      { type: "quiz", title: "Yoga quiz!", content: "Yoga helps you feel...", options: ["Calmer and stretched", "Only tired", "Angry", "Heavy"], correct: 0 },
    ],
  },
  {
    id: "motor-crawling-1",
    subjectId: "motor-skills",
    ageGroup: "2-4",
    title: "Crawling & Climbing",
    description: "Move in different ways",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Crawl and climb!", content: "Different ways to move build strong arms and legs!", character: "frog", visual: "🐛" },
      { type: "teach", title: "Bear crawl", content: "Hands and feet on floor, bottom up — like a bear!", character: "frog", visual: "🐻" },
      { type: "experiment", title: "Tunnel crawl!", content: "Crawl through a blanket tunnel!", experiment: { title: "Blanket Tunnel", materials: ["Chairs", "Blanket"], steps: ["Drape blanket over chairs", "Crawl through", "Pop out the end", "Celebrate!"] } },
      { type: "quiz", title: "Move quiz!", content: "Bear crawl uses...", options: ["Only one leg", "Arms and legs together", "Only head", "Wings"], correct: 1 },
    ],
  },
  {
    id: "motor-posture-1",
    subjectId: "motor-skills",
    ageGroup: "6-8",
    title: "Sitting Strong",
    description: "Posture for writing",
    coinsReward: 10,
    xpReward: 15,
    slides: [
      { type: "intro", title: "Posture!", content: "Good posture helps you write and focus longer!", character: "frog", visual: "🪑" },
      { type: "teach", title: "Feet flat", content: "Feet on floor, back straight, paper tilted!", character: "frog", visual: "✏️" },
      { type: "quiz", title: "Posture quiz!", content: "When writing, feet should be...", options: ["On the floor", "In the air", "On the table", "Crossed in air"], correct: 0 },
    ],
  },
];
